# ------------------------------------
# Copyright (c) DigitalOcean.
# Licensed under the Apache-2.0 License.
# ------------------------------------
# Generated by scripts/generate_inference_types.py — do not edit.
from __future__ import annotations

"""Typed response models for inference endpoints (auto-generated).

Usage::

    from pydo.types.chat import ChatCompletion
    from pydo.types.images import ImagesResponse, Image
    from pydo.types import ChatCompletion  # also works
"""

from pydo.types.async_invoke import AsyncInvokeResponse
from pydo.types.chat import ChatCompletionChunk
from pydo.types.chat import ChatCompletion
from pydo.types.chat import ChatCompletionStreamResponseDelta
from pydo.types.chat import ChatCompletionTokenLogprob
from pydo.types.chat import CompletionUsage
from pydo.types.images import Image
from pydo.types.images import ImageGenPartialImageEvent
from pydo.types.images import ImagesResponse
from pydo.types.images import ImagesUsage
from pydo.types.models import ListModelsResponse
from pydo.types.models import Model
from pydo.types.responses import Response
from pydo.types.responses import ResponseStreamChunk
from pydo.types.responses import ResponseUsage

__all__ = [
    "AsyncInvokeResponse",
    "ChatCompletionChunk",
    "ChatCompletion",
    "ChatCompletionStreamResponseDelta",
    "ChatCompletionTokenLogprob",
    "CompletionUsage",
    "Image",
    "ImageGenPartialImageEvent",
    "ImagesResponse",
    "ImagesUsage",
    "ListModelsResponse",
    "Model",
    "Response",
    "ResponseStreamChunk",
    "ResponseUsage",
]
