# ------------------------------------
# Copyright (c) DigitalOcean.
# Licensed under the Apache-2.0 License.
# ------------------------------------
# Generated by scripts/generate_inference_types.py — do not edit.
from __future__ import annotations


"""Auto-dispatch: maps the ``object`` field in JSON responses to typed classes."""

from typing import Dict, Type

from pydo.custom_extensions import DotDict

from pydo.types.chat import ChatCompletion, ChatCompletionChunk
from pydo.types.models import ListModelsResponse, Model
from pydo.types.responses import Response, ResponseStreamChunk


_OBJECT_TYPE_MAP: Dict[str, Type[DotDict]] = {
    "chat.completion": ChatCompletion,
    "chat.completion.chunk": ChatCompletionChunk,
    "list": ListModelsResponse,
    "model": Model,
    "response": Response,
    "response.chunk": ResponseStreamChunk,
}
