# ------------------------------------
# Copyright (c) DigitalOcean.
# Licensed under the Apache-2.0 License.
# ------------------------------------
# Generated by scripts/generate_inference_types.py — do not edit.
from __future__ import annotations

from typing import Any, List, Optional

from pydo.custom_extensions import DotDict


class ListModelsResponse(DotDict):
    """Typed response for ``list_models_response`` schema."""

    object: str  # The object type, which is always "list"
    data: List[Any]  # The list of available models


class Model(DotDict):
    """Typed response for ``model`` schema."""

    id: str  # The model identifier, which can be referenced in the API endpoints
    created: int  # The Unix timestamp (in seconds) when the model was created
    object: str  # The object type, which is always "model"
    owned_by: str  # The organization that owns the model


__all__ = ["ListModelsResponse", "Model"]
