"""Generate local fixture files for workspace transfer testing.

Writes into examples/agents/testdata/ (gitignored large binaries).

Usage:
  python examples/agents/generate_transfer_fixtures.py
  python examples/agents/generate_transfer_fixtures.py --sizes 1KiB,1MiB,40MiB
"""

from __future__ import annotations

import argparse
import hashlib
import os
import tarfile
import tempfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
OUT_DIR = HERE / "testdata"

# Default sizes: tiny (single part), medium, and large enough to force
# multiple ~16 MiB parts on typical CreateTransfer responses.
DEFAULT_SIZES = ("1KiB", "1MiB", "40MiB")

_UNITS = {
    "b": 1,
    "kb": 1000,
    "kib": 1024,
    "mb": 1000 * 1000,
    "mib": 1024 * 1024,
    "gb": 1000 * 1000 * 1000,
    "gib": 1024 * 1024 * 1024,
}


def _parse_size(text: str) -> int:
    raw = text.strip().lower().replace(" ", "")
    for suffix, mult in sorted(_UNITS.items(), key=lambda kv: -len(kv[0])):
        if raw.endswith(suffix):
            return int(float(raw[: -len(suffix)]) * mult)
    return int(raw)


def _write_patterned(path: Path, size: int) -> str:
    """Write *size* bytes of a repeating pattern; return lowercase sha256 hex."""
    path.parent.mkdir(parents=True, exist_ok=True)
    hasher = hashlib.sha256()
    # 256-byte pattern so multi-part boundaries are easy to eyeball in hexdumps.
    pattern = bytes((i % 256) for i in range(256))
    remaining = size
    with path.open("wb") as fh:
        while remaining > 0:
            chunk = pattern[: min(len(pattern), remaining)]
            fh.write(chunk)
            hasher.update(chunk)
            remaining -= len(chunk)
    return hasher.hexdigest()


def _write_tar(path: Path) -> str:
    """Create a small tar with two text members; return sha256 of the tar bytes."""
    path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory() as tmp:
        root = Path(tmp)
        (root / "hello.txt").write_text("hello from tarball\n", encoding="utf-8")
        nested = root / "nested"
        nested.mkdir()
        (nested / "world.txt").write_text("world\n", encoding="utf-8")
        with tarfile.open(path, "w") as tar:
            tar.add(root / "hello.txt", arcname="hello.txt")
            tar.add(nested / "world.txt", arcname="nested/world.txt")
    digest = hashlib.sha256(path.read_bytes()).hexdigest()
    return digest


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--sizes",
        default=",".join(DEFAULT_SIZES),
        help="Comma-separated sizes (e.g. 1KiB,1MiB,40MiB). Default: %(default)s",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=OUT_DIR,
        help=f"Output directory (default: {OUT_DIR})",
    )
    args = parser.parse_args()
    out: Path = args.out
    out.mkdir(parents=True, exist_ok=True)

    manifest_lines = ["# generated by generate_transfer_fixtures.py", ""]

    for label in [s.strip() for s in args.sizes.split(",") if s.strip()]:
        size = _parse_size(label)
        safe = label.replace(" ", "")
        path = out / f"blob_{safe}.bin"
        digest = _write_patterned(path, size)
        print(f"wrote {path}  size={size}  sha256={digest}")
        manifest_lines.append(f"{path.name}\t{size}\t{digest}")

    tar_path = out / "sample.tar"
    tar_digest = _write_tar(tar_path)
    print(f"wrote {tar_path}  size={tar_path.stat().st_size}  sha256={tar_digest}")
    manifest_lines.append(
        f"{tar_path.name}\t{tar_path.stat().st_size}\t{tar_digest}\tis_archive=true"
    )

    # Tiny committed-friendly text fixture (always regenerated).
    text_path = out / "hello.txt"
    text_path.write_text("hello from pydo staged transfer\n", encoding="utf-8")
    text_digest = hashlib.sha256(text_path.read_bytes()).hexdigest()
    print(f"wrote {text_path}  size={text_path.stat().st_size}  sha256={text_digest}")
    manifest_lines.append(
        f"{text_path.name}\t{text_path.stat().st_size}\t{text_digest}"
    )

    (out / "MANIFEST.tsv").write_text("\n".join(manifest_lines) + "\n", encoding="utf-8")
    print(f"\nmanifest: {out / 'MANIFEST.tsv'}")
    print(f"fixtures dir: {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
