# ------------------------------------
# Copyright (c) DigitalOcean.
# Licensed under the Apache-2.0 License.
# ------------------------------------
# Generated by scripts/generate_inference_types.py — do not edit.
from __future__ import annotations

from typing import Any, List, Optional

from pydo.custom_extensions import DotDict


class EmbeddingDataItem(DotDict):
    """Typed response for ``embedding_data_item`` schema."""

    index: int
    object: str  # The object type, which is always `embedding`
    embedding: Any


class EmbeddingsResponse(DotDict):
    """Typed response for ``embeddings_response`` schema."""

    object: str  # The object type, which is always the string `list`
    model: str  # The embedding model that produced the vectors
    data: List[Any]  # One entry for each `input` string, in the same order
    usage: "EmbeddingsUsage"


class EmbeddingsUsage(DotDict):
    """Typed response for ``embeddings_usage`` schema."""

    prompt_tokens: int  # Number of input tokens used for the embedding
    total_tokens: int  # Total billable tokens for the request


__all__ = ["EmbeddingDataItem", "EmbeddingsResponse", "EmbeddingsUsage"]
