# ------------------------------------
# Copyright (c) DigitalOcean.
# Licensed under the Apache-2.0 License.
# ------------------------------------
# Generated by scripts/generate_inference_types.py — do not edit.
from __future__ import annotations

from typing import Any, Optional

from pydo.custom_extensions import DotDict


class Error(DotDict):
    """Typed response for ``error`` schema."""

    id: str
    message: str
    request_id: str


class SystemoneAnswer(DotDict):
    """Typed response for ``systemone_answer`` schema."""

    type: str  # Echoes the `type` of the question this answer corresponds to
    noul: float  # Present when the question type is `noul`. A truth-likelihood value
    choice: str
    score: float
    legend: Any
    probabilities: Any  # Calibrated probability for each possible answer value
    confidence: float  # Overall calibrated confidence in the returned answer


class SystemoneResponse(DotDict):
    """Typed response for ``systemone_response`` schema."""

    model: str  # Model ID that produced the response
    answers: Any
    usage: "SystemoneUsage"


class SystemoneUsage(DotDict):
    """Typed response for ``systemone_usage`` schema."""

    input_tokens: int  # Number of input tokens consumed by the request
    output_tokens: int


__all__ = ["Error", "SystemoneAnswer", "SystemoneResponse", "SystemoneUsage"]
