# ------------------------------------
# Copyright (c) DigitalOcean.
# Licensed under the Apache-2.0 License.
# ------------------------------------
# Generated by scripts/generate_inference_resources.py — do not edit.
from __future__ import annotations


from pydo import Client
from typing import Any
from .generations import Generations


class Images:
    """Inference path namespace (generated)."""

    def __init__(self, client: Client) -> None:
        self.generations = Generations(client)

    def generate(self, **kwargs: Any) -> Any:
        """Alias for ``images.generations.generate`` (``POST /v1/images/generations``)."""
        return self.generations.generate(**kwargs)


__all__ = ["Images"]
