# ------------------------------------
# Copyright (c) DigitalOcean.
# Licensed under the Apache-2.0 License.
# ------------------------------------
# Generated by scripts/generate_inference_resources.py — do not edit.
from __future__ import annotations

"""Async inference resource packages (e.g. ``pydo.resources.aio.inference``)."""

__all__ = []
