# ------------------------------------
# Copyright (c) DigitalOcean.
# Licensed under the Apache-2.0 License.
# ------------------------------------
# Generated by scripts/generate_inference_types.py — do not edit.
from __future__ import annotations

from typing import Any, List, Optional

from pydo.custom_extensions import DotDict


class Image(DotDict):
    """Typed response for ``generated_image`` schema."""

    b64_json: str
    revised_prompt: str


class ImageGenPartialImageEvent(DotDict):
    """Typed response for ``image_gen_partial_image_event`` schema."""

    type: str  # The type of the event. Always `image_generation.partial_image`
    b64_json: str
    created_at: int  # The Unix timestamp when the event was created
    size: str  # The size of the requested image
    quality: str  # The quality setting for the requested image
    background: str  # The background setting for the requested image
    output_format: str  # The output format for the requested image
    partial_image_index: int  # 0-based index for the partial image (streaming)


class ImagesResponse(DotDict):
    """Typed response for ``images_response`` schema."""

    created: int  # The Unix timestamp (in seconds) of when the images were created
    data: List[Any]  # The list of generated images
    background: Optional[str]  # The background setting used for the image generation
    output_format: Optional[str]  # The output format of the generated image
    quality: Optional[str]  # The quality setting used for the image generation
    size: Optional[str]  # The size of the generated image
    usage: Optional[Any]  # Usage statistics for the image generation request


class ImagesUsage(DotDict):
    """Typed response for ``images_usage`` schema."""

    total_tokens: int
    input_tokens: int  # The number of tokens (images and text) in the input prompt
    output_tokens: int  # The number of image tokens in the output image
    input_tokens_details: Any  # Detailed breakdown of input tokens


__all__ = ["Image", "ImageGenPartialImageEvent", "ImagesResponse", "ImagesUsage"]
