# ------------------------------------
# Copyright (c) DigitalOcean.
# Licensed under the Apache-2.0 License.
# ------------------------------------
# Generated by scripts/generate_inference_resources.py — do not edit.
from __future__ import annotations


from typing import Any


class InferenceClientSurface:
    """Generated shortcuts for serverless inference (discovered from the published spec)."""

    @property
    def async_invoke(self) -> Any:
        """Nested serverless inference API under path segment ``async_invoke``."""

        return self._require_inference_resource_root().async_invoke

    @property
    def batches(self) -> Any:
        """Nested serverless inference API under path segment ``batches``."""

        return self._require_inference_resource_root().batches

    @property
    def chat(self) -> Any:
        """Nested serverless inference API under path segment ``chat``."""

        return self._require_inference_resource_root().chat

    @property
    def embeddings(self) -> Any:
        """Nested serverless inference API under path segment ``embeddings``."""

        return self._require_inference_resource_root().embeddings

    @property
    def files(self) -> Any:
        """Nested serverless inference API under path segment ``files``."""

        return self._require_inference_resource_root().files

    @property
    def messages(self) -> Any:
        """Nested serverless inference API under path segment ``messages``."""

        return self._require_inference_resource_root().messages

    @property
    def models(self) -> Any:
        """Nested serverless inference API under path segment ``models``."""

        return self._require_inference_resource_root().models

    @property
    def responses(self) -> Any:
        """Nested serverless inference API under path segment ``responses``."""

        return self._require_inference_resource_root().responses

    @property
    def audio(self) -> Any:
        """Audio namespace (TTS + generation via async-invoke)."""

        return self._require_inference_resource_root().async_invoke.audio

    @property
    def speech(self) -> Any:
        """TTS entry: same as ``audio.speech`` (async-invoke)."""

        return self._require_inference_resource_root().async_invoke.audio.speech

    @property
    def async_images(self) -> Any:
        """Async image generation: same as ``async_invoke.images``."""

        return self._require_inference_resource_root().async_invoke.images

    @property
    def inference_layout(self) -> Any:
        """Full nested serverless inference layout (same objects as the shortcuts above)."""

        return self._require_inference_resource_root()


class AgentClientSurface:
    """Generated shortcut for agent inference operations."""

    @property
    def agent(self) -> Any:
        """Nested agent inference API (``agent_inference`` operation group)."""

        return self._require_agent_inference_resource_root()


__all__ = ["AgentClientSurface", "InferenceClientSurface"]
