# ------------------------------------
# Copyright (c) DigitalOcean.
# Licensed under the Apache-2.0 License.
# ------------------------------------
# Generated by scripts/generate_inference_resources.py — do not edit.
"""Async inference-focused entry point: ``from pydo.inference.aio import Client``.

Asynchronous twin of :class:`pydo.inference.Client`. Same surface,
``await``-friendly. See :mod:`pydo.inference` for usage details.
"""
from __future__ import annotations

from typing import List, Optional

from pydo.aio import Client as _DigitalOceanClient
from pydo.aio._patch import TokenCredentials
from pydo.custom_extensions import INFERENCE_BASE_URL


# Top-level attributes that the namespaced ``Client`` advertises via
# ``dir()``. Populated by ``scripts/generate_inference_resources.py``
# from the discovered OpenAPI surface plus cross-resource shortcuts.
_INFERENCE_NAMESPACES: tuple = (
    "agent",
    "async_images",
    "async_invoke",
    "audio",
    "batches",
    "chat",
    "embeddings",
    "files",
    "images",
    "inference_layout",
    "messages",
    "models",
    "responses",
    "speech",
)


class Client(_DigitalOceanClient):
    """Inference-focused DigitalOcean async client.

    Asynchronous counterpart to :class:`pydo.inference.Client`. Every
    inference / agent-inference surface is exposed as an awaitable
    method, while the underlying :class:`pydo.aio.Client` machinery
    (authentication, transport pipeline, multi-base-URL routing, SSE
    streaming) is reused unchanged.
    """

    def __init__(
        self,
        token: Optional[str] = None,
        *,
        api_key: Optional[str] = None,
        timeout: int = 120,
        inference_endpoint: str = INFERENCE_BASE_URL,
        agent_endpoint: str = "",
        **kwargs,
    ) -> None:
        super().__init__(
            token=token,
            api_key=api_key,
            timeout=timeout,
            inference_endpoint=inference_endpoint,
            agent_endpoint=agent_endpoint,
            **kwargs,
        )

    def __dir__(self) -> List[str]:
        return sorted(set(_INFERENCE_NAMESPACES))

    def __repr__(self) -> str:
        return "<pydo.inference.aio.Client>"


__all__ = ["Client", "TokenCredentials"]
