# ------------------------------------
# Copyright (c) DigitalOcean.
# Licensed under the Apache-2.0 License.
# ------------------------------------
# Generated by scripts/generate_inference_types.py — do not edit.
from __future__ import annotations

from typing import Any, List, Optional

from pydo.custom_extensions import DotDict


class Batch(DotDict):
    """Typed response for ``batch`` schema."""

    batch_id: str  # Unique identifier for the batch job
    status: str
    provider: str
    endpoint: str  # Inference endpoint each request is dispatched to
    completion_window: str
    input_file_id: str  # The uploaded JSONL input file
    output_file_id: Optional[str]  # Output JSONL file. Populated once the job completes
    error_file_id: Optional[
        str
    ]  # Error sidecar file. Null when no errors were produced
    request_counts: Any  # Aggregate request counts
    request_id: str  # The idempotency key supplied at creation
    metadata: Optional[Any]  # Metadata attached at creation
    errors: Optional[
        List[Any]
    ]  # Top-level errors that prevented the batch from completing
    created_at: str
    in_progress_at: Optional[str]
    finalizing_at: Optional[str]
    completed_at: Optional[str]
    expires_at: Optional[str]  # Derived from `created_at` plus `completion_window`
    cancelled_at: Optional[str]
    failed_at: Optional[str]


class BatchFileCreateResponse(DotDict):
    """Typed response for ``batch_file_create_response`` schema."""

    file_id: str  # Pass this value as `file_id` when creating a batch job
    upload_url: str
    expires_at: Optional[str]  # When `upload_url` expires


class BatchResultsResponse(DotDict):
    """Typed response for ``batch_results_response`` schema."""

    batch_id: str
    result_available: bool
    output_file_url: Optional[str]  # Presigned URL for the main results JSONL
    error_file_url: Optional[str]  # Presigned URL for the error sidecar JSONL, if any
    expires_at: Optional[str]  # When the presigned URLs expire


class Error(DotDict):
    """Typed response for ``error`` schema."""

    id: str
    message: str
    request_id: str


__all__ = ["Batch", "BatchFileCreateResponse", "BatchResultsResponse", "Error"]
