# ------------------------------------
# Copyright (c) DigitalOcean.
# Licensed under the Apache-2.0 License.
# ------------------------------------
# Generated by scripts/generate_inference_types.py — do not edit.
from __future__ import annotations

from typing import Any, List, Optional

from pydo.custom_extensions import DotDict


class BatchFileCreateResponse(DotDict):
    """Typed response for ``batch_file_create_response`` schema."""

    file_id: str  # Pass this value as `file_id` when creating a batch job
    upload_url: str
    expires_at: Optional[str]  # When `upload_url` expires


class BatchListResponse(DotDict):
    """Typed response for ``batch_list_response`` schema."""

    object: str  # The object type, always `list`
    data: List[Any]  # Batch jobs on this page, ordered newest first
    first_id: Optional[
        str
    ]  # ID of the first batch on this page. Null when the page is empty
    last_id: Optional[str]
    has_more: bool  # Whether additional batches exist beyond this page


class BatchResultsResponse(DotDict):
    """Typed response for ``batch_results_response`` schema."""

    batch_id: str
    result_available: bool
    output_file_url: Optional[str]  # Presigned URL for the main results JSONL
    error_file_url: Optional[str]  # Presigned URL for the error sidecar JSONL, if any
    expires_at: Optional[str]  # When the presigned URLs expire


class Error(DotDict):
    """Typed response for ``error`` schema."""

    id: str
    message: str
    request_id: str


__all__ = [
    "BatchFileCreateResponse",
    "BatchListResponse",
    "BatchResultsResponse",
    "Error",
]
