# ------------------------------------
# Copyright (c) DigitalOcean.
# Licensed under the Apache-2.0 License.
# ------------------------------------
# Generated by scripts/generate_inference_resources.py — do not edit.
from __future__ import annotations

from typing import Any

from pydo.aio import Client
from pydo.custom_extensions import _wrap

_SDK_KWARGS = frozenset(
    {
        "cls",
        "content_type",
        "continuation_token",
        "error_map",
        "form_content_type",
        "headers",
        "params",
        "polling",
        "raw_request_hook",
        "raw_response_hook",
    }
)


class AsyncInvokeImages:
    """Async image generation helper."""

    def __init__(self, parent: "AsyncInvoke") -> None:
        self._parent = parent

    async def generate(
        self,
        *,
        prompt: str,
        model_id: str,
        tags: Any = None,
        **kwargs: Any,
    ) -> Any:
        """Generate an image — maps to ``model_id`` and ``input.prompt``."""
        sdk = {k: v for k, v in kwargs.items() if k in _SDK_KWARGS}
        rest = {k: v for k, v in kwargs.items() if k not in _SDK_KWARGS}
        inp = {**rest, "prompt": prompt}
        payload = {"model_id": model_id, "input": inp}
        if tags is not None:
            payload["tags"] = tags
        return await self._parent.create(**payload, **sdk)


class AsyncInvokeSpeech:
    """Text-to-speech helper."""

    def __init__(self, parent: "AsyncInvoke") -> None:
        self._parent = parent

    async def create(
        self,
        *,
        input: str,
        model_id: str,
        tags: Any = None,
        **kwargs: Any,
    ) -> Any:
        """Create speech from text — maps ``input`` to ``input.text``."""
        sdk = {k: v for k, v in kwargs.items() if k in _SDK_KWARGS}
        rest = {k: v for k, v in kwargs.items() if k not in _SDK_KWARGS}
        inp = {**rest, "text": input}
        payload = {"model_id": model_id, "input": inp}
        if tags is not None:
            payload["tags"] = tags
        return await self._parent.create(**payload, **sdk)


class AsyncInvokeAudio:
    """Audio namespace (generation + ``speech`` for TTS)."""

    def __init__(self, parent: "AsyncInvoke") -> None:
        self._root = parent
        self.speech = AsyncInvokeSpeech(parent)

    async def generate(
        self,
        *,
        prompt: str,
        model_id: str,
        seconds_total: Any = None,
        tags: Any = None,
        **kwargs: Any,
    ) -> Any:
        """Async music / text-to-audio (``input.prompt``, ``seconds_total``, …)."""
        sdk = {k: v for k, v in kwargs.items() if k in _SDK_KWARGS}
        rest = {k: v for k, v in kwargs.items() if k not in _SDK_KWARGS}
        inp = {**rest, "prompt": prompt}
        if seconds_total is not None:
            inp["seconds_total"] = seconds_total
        payload = {"model_id": model_id, "input": inp}
        if tags is not None:
            payload["tags"] = tags
        return await self._root.create(**payload, **sdk)


class AsyncInvoke:
    """Inference resource helper with nested async helpers."""

    def __init__(self, client: Client) -> None:
        self._client = client
        self.images = AsyncInvokeImages(self)
        self.audio = AsyncInvokeAudio(self)

    async def create(self, **kwargs: Any) -> Any:
        """Delegates to ``client.inference.create_async_invoke``."""
        body = {k: v for k, v in kwargs.items() if k not in _SDK_KWARGS}
        sdk = {k: v for k, v in kwargs.items() if k in _SDK_KWARGS}
        return _wrap(await self._client.inference.create_async_invoke(body, **sdk))
