# ------------------------------------
# Copyright (c) DigitalOcean.
# Licensed under the Apache-2.0 License.
# ------------------------------------
# Generated by scripts/generate_inference_resources.py — do not edit.
from __future__ import annotations

import asyncio
from typing import Any

from pydo.aio import Client
from pydo.custom_extensions import (
    _SDK_KWARGS,
    _FileContent,
    _read_file_arg,
    _upload_via_presigned,
    _wrap,
    _wrap_file_content,
)


class Files:
    """Convenience facade for JSONL input upload and output download."""

    def __init__(self, client: Client) -> None:
        self._client = client

    async def create(
        self,
        *,
        file: Any = None,
        purpose: str = "batch",
        **kwargs: Any,
    ) -> Any:
        """Upload a JSONL input file for use with ``batches.create``.

        Combines two spec operations: creating a file intent
        (``POST /v1/batches/files``) and uploading bytes to the returned
        presigned URL.  Returns an object exposing both the canonical
        spec fields (``file_id``, ``upload_url``, ``expires_at``) and an
        ``id`` alias.

        :keyword file: File content; accepts a filesystem path, raw bytes,
            a readable stream, or a ``(name, data)`` tuple. Required.
        :keyword purpose: Free-form label retained on the returned object
            (``"batch"`` is the only purpose currently used server-side).
        """
        name, data, content_type = _read_file_arg(file)
        sdk = {k: v for k, v in kwargs.items() if k in _SDK_KWARGS}
        intent = await self._client.inference.create_batch_file(
            {"file_name": name}, **sdk
        )
        await asyncio.to_thread(
            _upload_via_presigned, intent["upload_url"], data, content_type
        )
        result = dict(intent)
        result["id"] = result.get("file_id")
        result["purpose"] = purpose
        result["filename"] = name
        result["bytes"] = len(data)
        return _wrap(result)

    async def content(self, file_id: str, **kwargs: Any) -> _FileContent:
        """Fetch the output of a completed batch job.

        ``file_id`` may be the value read from ``batch.output_file_id`` on
        a completed batch.  Delegates to ``get_batch_results`` and returns
        a response object whose ``.read()`` / ``.text`` accessors lazily
        download the referenced presigned URL.
        """
        response = await self._client.inference.get_batch_results(
            batch_id=file_id, **kwargs
        )
        return _wrap_file_content(response)


__all__ = ["Files"]
