# ------------------------------------
# Copyright (c) DigitalOcean.
# Licensed under the Apache-2.0 License.
# ------------------------------------
# Generated by scripts/generate_inference_resources.py — do not edit.
from __future__ import annotations

from typing import Any

from pydo.aio import Client
from pydo.custom_extensions import (
    _SDK_KWARGS,
    _prepare_body,
    _wrap,
    _wrap_with_id_alias,
)


class Models:
    """Inference resource helper (generated)."""

    def __init__(self, client: Client) -> None:
        self._client = client

    async def list(self, **kwargs: Any) -> Any:
        """Delegates to ``client.inference.list_models``."""
        return _wrap(await self._client.inference.list_models(**kwargs))
