# ------------------------------------
# Copyright (c) DigitalOcean.
# Licensed under the Apache-2.0 License.
# ------------------------------------
# Generated by scripts/generate_inference_resources.py — do not edit.
from __future__ import annotations

from typing import Any

from pydo.aio import Client
from pydo.custom_extensions import _wrap

_SDK_KWARGS = frozenset(
    {
        "cls",
        "content_type",
        "continuation_token",
        "error_map",
        "form_content_type",
        "headers",
        "params",
        "polling",
        "raw_request_hook",
        "raw_response_hook",
    }
)


class Completions:
    """Inference resource helper (generated)."""

    def __init__(self, client: Client) -> None:
        self._client = client

    async def create(self, **kwargs: Any) -> Any:
        """Delegates to ``client.agent_inference.create_chat_completion``."""
        body = {k: v for k, v in kwargs.items() if k not in _SDK_KWARGS}
        sdk = {k: v for k, v in kwargs.items() if k in _SDK_KWARGS}
        return _wrap(
            await self._client.agent_inference.create_chat_completion(body, **sdk)
        )
