# ------------------------------------
# Copyright (c) DigitalOcean.
# Licensed under the Apache-2.0 License.
# ------------------------------------
# Generated by scripts/generate_inference_resources.py — do not edit.
from __future__ import annotations


from pydo.aio import Client
from .completions import Completions


class Chat:
    """Inference path namespace (generated)."""

    def __init__(self, client: Client) -> None:
        self.completions = Completions(client)


__all__ = ["Chat"]
