# ------------------------------------
# Copyright (c) DigitalOcean.
# Licensed under the Apache-2.0 License.
# ------------------------------------
# Generated by scripts/generate_inference_types.py — do not edit.
from __future__ import annotations

from typing import Any, List, Optional

from pydo.custom_extensions import DotDict


class Response(DotDict):
    """Typed response for ``create_response_response`` schema."""

    id: str  # A unique identifier for the response
    object: str  # The object type, which is always `response`
    created: int  # The Unix timestamp (in seconds) of when the response was created
    model: str  # The model used to generate the response
    output: List[Any]
    usage: "ResponseUsage"
    parallel_tool_calls: Optional[bool]  # Whether parallel tool calls are enabled
    temperature: Optional[float]  # Temperature setting used for the response
    tool_choice: Optional[str]  # Tool choice setting used for the response
    tools: Optional[List[Any]]  # Tools available for the response
    top_p: Optional[float]  # Top-p setting used for the response
    max_output_tokens: Optional[int]  # Maximum output tokens setting
    status: Optional[str]  # Status of the response
    user: Optional[str]  # User identifier


class ResponseStreamChunk(DotDict):
    """Typed response for ``create_response_stream_response`` schema."""

    id: str  # A unique identifier for the response. Each chunk has the same ID
    object: str  # The object type, which is always `response.chunk`
    created: int
    model: str  # The model used to generate the response
    choices: List[Any]
    usage: Optional[Any]


class ResponseUsage(DotDict):
    """Typed response for ``response_usage`` schema."""

    input_tokens: int  # The number of input tokens
    input_tokens_details: Any  # A detailed breakdown of the input tokens
    output_tokens: int  # The number of output tokens
    output_tokens_details: Any  # A detailed breakdown of the output tokens
    total_tokens: int  # The total number of tokens used


__all__ = ["Response", "ResponseStreamChunk", "ResponseUsage"]
