# ------------------------------------
# Copyright (c) DigitalOcean.
# Licensed under the Apache-2.0 License.
# ------------------------------------
# Generated by scripts/generate_inference_resources.py — do not edit.
from __future__ import annotations

from typing import Any

from pydo.aio import Client
from pydo.custom_extensions import (
    _SDK_KWARGS,
    _prepare_body,
    _wrap,
    _wrap_with_id_alias,
)


class Generations:
    """Inference resource helper (generated)."""

    def __init__(self, client: Client) -> None:
        self._client = client

    async def generate(self, **kwargs: Any) -> Any:
        """Delegates to ``client.inference.create_image``."""
        body = {k: v for k, v in kwargs.items() if k not in _SDK_KWARGS}
        sdk = {k: v for k, v in kwargs.items() if k in _SDK_KWARGS}
        body = _prepare_body("create_image", body)
        return _wrap_with_id_alias(
            await self._client.inference.create_image(body, **sdk),
            primary_id_field="image_id",
        )
