# ------------------------------------
# Copyright (c) DigitalOcean.
# Licensed under the Apache-2.0 License.
# ------------------------------------
# Generated by scripts/generate_inference_types.py — do not edit.
from __future__ import annotations

from typing import Any, List, Optional

from pydo.custom_extensions import DotDict


class ChatCompletionChunk(DotDict):
    """Typed response for ``chat_completion_chunk`` schema."""

    id: str
    choices: List[Any]
    created: int
    model: str  # The model to generate the completion
    object: str  # The object type, which is always chat.completion.chunk
    usage: Optional[Any]


class ChatCompletion(DotDict):
    """Typed response for ``chat_completion_response`` schema."""

    id: str  # A unique identifier for the chat completion
    choices: List[Any]
    created: int
    model: str  # The model used for the chat completion
    object: str  # The object type, which is always chat.completion
    usage: "CompletionUsage"


class ChatCompletionStreamResponseDelta(DotDict):
    """Typed response for ``chat_completion_stream_response_delta`` schema."""

    content: Optional[str]  # The contents of the chunk message
    tool_calls: List[Any]
    reasoning_content: Optional[str]  # The reasoning content generated by the model
    role: str  # The role of the author of this message
    refusal: Optional[str]  # The refusal message generated by the model


class ChatCompletionTokenLogprob(DotDict):
    """Typed response for ``chat_completion_token_logprob`` schema."""

    token: str  # The token
    logprob: float
    bytes: Optional[List[Any]]
    top_logprobs: List[Any]


class CompletionUsage(DotDict):
    """Typed response for ``completion_usage`` schema."""

    completion_tokens: int  # Number of tokens in the generated completion
    prompt_tokens: int  # Number of tokens in the prompt
    cache_created_input_tokens: int  # Number of prompt tokens written to cache
    cache_creation: Any  # Breakdown of prompt tokens written to cache
    cache_read_input_tokens: int  # Number of prompt tokens read from cache
    total_tokens: (
        int  # Total number of tokens used in the request (prompt + completion)
    )


__all__ = [
    "ChatCompletionChunk",
    "ChatCompletion",
    "ChatCompletionStreamResponseDelta",
    "ChatCompletionTokenLogprob",
    "CompletionUsage",
]
