# ------------------------------------
# Copyright (c) DigitalOcean.
# Licensed under the Apache-2.0 License.
# ------------------------------------
# Generated by scripts/generate_inference_types.py — do not edit.
from __future__ import annotations

from typing import Any, List, Optional

from pydo.custom_extensions import DotDict


class MessagesCreateErrorResponse(DotDict):
    """Typed response for ``messages_create_error_response`` schema."""

    type: str
    error: Any


class MessagesCreateResponse(DotDict):
    """Typed response for ``messages_create_response`` schema."""

    id: str  # Unique identifier for this message object
    type: str  # Object type discriminator
    role: str  # Always `assistant` for this response
    content: List[Any]  # Assistant output blocks (`text` and/or `tool_use`)
    model: str  # Model that produced the message
    stop_reason: Optional[str]  # Why generation stopped
    stop_sequence: Optional[
        str
    ]  # When `stop_reason` is `stop_sequence`, the sequence that matched
    usage: "MessagesUsage"


class MessagesResponseContentBlock(DotDict):
    """Typed response for ``messages_response_content_block`` schema."""

    input_tokens: int  # Number of input tokens billed for this request
    output_tokens: int  # Number of output tokens generated
    cache_creation_input_tokens: (
        int  # Input tokens used to create a prompt cache entry, if applicable
    )
    cache_read_input_tokens: int  # Input tokens read from a prompt cache, if applicable
    speed: Optional[str]  # Inference speed tier reflected in billing or routing


class MessagesStreamEvent(DotDict):
    """Typed response for ``messages_stream_event`` schema."""

    type: str  # SSE event type
    message: Any  # Present on `message_start`; initial message metadata
    index: int  # Index of the content block this event refers to
    content_block: Any  # Present on `content_block_start`
    delta: Any  # Present on `content_block_delta` and `message_delta`
    usage: Any  # Streamed usage (for example on `message_delta`)


class MessagesUsage(DotDict):
    """Typed response for ``messages_usage`` schema."""

    input_tokens: int  # Number of input tokens billed for this request
    output_tokens: int  # Number of output tokens generated
    cache_creation_input_tokens: (
        int  # Input tokens used to create a prompt cache entry, if applicable
    )
    cache_read_input_tokens: int  # Input tokens read from a prompt cache, if applicable
    speed: Optional[str]  # Inference speed tier reflected in billing or routing


__all__ = [
    "MessagesCreateErrorResponse",
    "MessagesCreateResponse",
    "MessagesResponseContentBlock",
    "MessagesStreamEvent",
    "MessagesUsage",
]
