# ------------------------------------
# Copyright (c) DigitalOcean.
# Licensed under the Apache-2.0 License.
# ------------------------------------
# Generated by scripts/generate_inference_resources.py — do not edit.
from __future__ import annotations


from typing import Any

from pydo.aio import Client
from pydo.custom_extensions import (
    _SDK_KWARGS,
    _prepare_body,
    _wrap,
    _wrap_with_id_alias,
)
from .files import Files
from .results import Results


class Batches:
    """Inference resource helper (generated)."""

    def __init__(self, client: Client) -> None:
        self._client = client
        self.files = Files(client)
        self.results = Results(client)

    async def list(self, **kwargs: Any) -> Any:
        """Delegates to ``client.inference.list_batches``."""
        return _wrap(await self._client.inference.list_batches(**kwargs))

    async def create(self, **kwargs: Any) -> Any:
        """Delegates to ``client.inference.create_batch``."""
        body = {k: v for k, v in kwargs.items() if k not in _SDK_KWARGS}
        sdk = {k: v for k, v in kwargs.items() if k in _SDK_KWARGS}
        body = _prepare_body("create_batch", body)
        return _wrap_with_id_alias(
            await self._client.inference.create_batch(body, **sdk),
            primary_id_field="batch_id",
        )

    async def get(self, batch_id: str, **kwargs: Any) -> Any:
        """Delegates to ``client.inference.get_batch``."""
        return _wrap_with_id_alias(
            await self._client.inference.get_batch(batch_id=batch_id, **kwargs),
            primary_id_field="batch_id",
        )

    retrieve = get

    async def cancel(self, batch_id: str, **kwargs: Any) -> Any:
        """Delegates to ``client.inference.cancel_batch``."""
        return _wrap(
            await self._client.inference.cancel_batch(batch_id=batch_id, **kwargs)
        )


__all__ = ["Batches"]
