# ------------------------------------
# Copyright (c) DigitalOcean.
# Licensed under the Apache-2.0 License.
# ------------------------------------
# Generated by scripts/generate_inference_resources.py — do not edit.
"""Inference-focused entry point: ``from pydo.inference import Client``.

This namespace gives serverless-inference and agent-inference callers a
purpose-built ``Client`` that mirrors the conventions used by other
LLM SDKs (``Client(token=...)`` / ``Client(api_key=...)``) while staying
fully integrated with :mod:`pydo` — the same authentication, transport
pipeline, retry, logging and response wrappers are reused under the hood.

The list of top-level namespaces exposed on this client
(``chat``, ``models``, ``embeddings``, ``images``, ``responses``,
``batches``, ``audio``, ``speech``, ``files``, ``agent`` …) is derived
from the OpenAPI spec at code-generation time, so any inference endpoint
added to the spec in the future surfaces here automatically — no manual
edits to this module are required.

Example::

    import os
    from pydo.inference import Client

    client = Client(token=os.environ["DIGITALOCEAN_TOKEN"])

    resp = client.chat.completions.create(
        model="llama3.3-70b-instruct",
        messages=[{"role": "user", "content": "Hello!"}],
    )
"""
from __future__ import annotations

from typing import List, Optional

from pydo import Client as _DigitalOceanClient
from pydo._patch import TokenCredentials
from pydo.custom_extensions import INFERENCE_BASE_URL


# Top-level attributes that the namespaced ``Client`` advertises via
# ``dir()``. Populated by ``scripts/generate_inference_resources.py``
# from the discovered OpenAPI surface plus cross-resource shortcuts.
_INFERENCE_NAMESPACES: tuple = (
    "agent",
    "async_images",
    "async_invoke",
    "audio",
    "batches",
    "chat",
    "embeddings",
    "files",
    "images",
    "inference_layout",
    "messages",
    "models",
    "responses",
    "speech",
)


class Client(_DigitalOceanClient):
    """Inference-focused DigitalOcean Python client.

    A drop-in entry point under ``pydo.inference`` for callers whose
    workload is serverless inference (chat completions, embeddings,
    image / audio generation, batch inference, agent inference, …).

    Inherits the full :class:`pydo.Client` machinery — authentication,
    transport pipeline, multi-base-URL routing and SSE streaming — so
    every inference surface that works on ``pydo.Client`` also works
    here. The top-level attribute surface, however, is narrowed to the
    inference and agent-inference namespaces so editor autocomplete
    (and ``dir(client)``) stay focused on inference primitives.
    """

    def __init__(
        self,
        token: Optional[str] = None,
        *,
        api_key: Optional[str] = None,
        timeout: int = 120,
        inference_endpoint: str = INFERENCE_BASE_URL,
        agent_endpoint: str = "",
        **kwargs,
    ) -> None:
        super().__init__(
            token=token,
            api_key=api_key,
            timeout=timeout,
            inference_endpoint=inference_endpoint,
            agent_endpoint=agent_endpoint,
            **kwargs,
        )

    def __dir__(self) -> List[str]:
        return sorted(set(_INFERENCE_NAMESPACES))

    def __repr__(self) -> str:
        return "<pydo.inference.Client>"


__all__ = ["Client", "TokenCredentials"]
