# ------------------------------------
# Copyright (c) DigitalOcean.
# Licensed under the Apache-2.0 License.
# ------------------------------------
# Generated by scripts/generate_inference_types.py — do not edit.
from __future__ import annotations

from typing import Any, Optional

from pydo.custom_extensions import DotDict


class AsyncInvokeResponse(DotDict):
    """Typed response for ``async_invoke_response`` schema."""

    request_id: str
    status: str  # The current status of the async invocation
    model_id: str  # The model ID that was invoked
    created_at: str  # The timestamp when the request was created
    started_at: Optional[
        str
    ]  # The timestamp when the job started processing. Null while queued
    completed_at: Optional[
        str
    ]  # The timestamp when the job completed. Null until finished
    output: Optional[Any]
    error: Optional[str]  # Error message if the job failed. Null on success


__all__ = ["AsyncInvokeResponse"]
