#!/usr/bin/env python3
# ------------------------------------
# Copyright (c) DigitalOcean.
# Licensed under the Apache-2.0 License.
# ------------------------------------
"""Emit nested ``src/pydo/resources/`` packages for inference HTTP paths.

**Source of truth:** only ``build_inference_*`` / ``build_agent_inference_*``
helpers in ``operations/_operations.py`` (Autorest output from the OpenAPI
spec).  Droplet / v2 APIs are not read here.

For each inference URL, path segments become nested modules/classes; method
names map from operation names (``list_*`` → ``list``, ``create_image`` →
``generate``, etc.).  Keyword arguments on generated helpers are passed into
the JSON body (except SDK kwargs like ``headers``, ``cls``), matching the
schema Autorest embedded for each operation.

Also emits ``client_surface*.py`` mixins so :class:`pydo.Client` shortcuts
(``chat``, ``models``, ``inference_layout``, ``agent``, …) track whatever the
spec contains — no hand-maintained list in ``_patch.py``.

For ``POST /v1/images/generations``, :class:`pydo.Client` injects
``client.images.generate`` onto the v2 Images API object (see ``_patch.py``).
Shortcuts: ``client.audio`` / ``client.speech`` / ``client.async_images`` for
async-invoke; ``async_invoke`` exposes ``.images`` / ``.audio`` under
``inference_layout``.

Run after Autorest (``make generate``).
"""
from __future__ import annotations

import json
import re
import shutil
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, List, Optional, Set, Tuple

ROOT = Path(__file__).resolve().parents[1]
OPS_PATH = ROOT / "src/pydo/operations/_operations.py"
OUT_ROOT = ROOT / "src/pydo/resources"
NAMESPACE_ROOT = ROOT / "src/pydo/inference"

# Cross-resource shortcuts that ``_write_client_surface`` adds to
# :class:`InferenceClientSurface` on top of the spec-discovered top-level
# segments. Kept in sync with the generator's emission rules below.
_INFERENCE_SURFACE_EXTRAS = ("audio", "speech", "async_images", "inference_layout")
_AGENT_SURFACE_EXTRAS = ("agent",)

BUILD_RE = re.compile(
    r"^def build_(?P<group>inference|agent_inference)_(?P<op>.+)_request\b"
)
URL_RE = re.compile(r'_url\s*=\s*["\'](?P<url>[^"\']+)["\']')

_SDK_KWARGS = frozenset(
    {
        "headers",
        "params",
        "content_type",
        "cls",
        "raw_request_hook",
        "raw_response_hook",
        "polling",
        "continuation_token",
        "form_content_type",
        "error_map",
    }
)


def _header(*, async_mode: bool) -> str:
    """Common prelude for every generated resource module.

    Individual writers append their own ``from pydo.custom_extensions
    import ...`` block so the imports stay consolidated and explicit.
    """
    client_import = (
        "from pydo.aio import Client" if async_mode else "from pydo import Client"
    )
    return (
        "# ------------------------------------\n"
        "# Copyright (c) DigitalOcean.\n"
        "# Licensed under the Apache-2.0 License.\n"
        "# ------------------------------------\n"
        "# Generated by scripts/generate_inference_resources.py — do not edit.\n"
        "from __future__ import annotations\n"
        "\n"
        "from typing import Any\n"
        "\n"
        f"{client_import}\n"
    )


INIT_HEADER = (
    "# ------------------------------------\n"
    "# Copyright (c) DigitalOcean.\n"
    "# Licensed under the Apache-2.0 License.\n"
    "# ------------------------------------\n"
    "# Generated by scripts/generate_inference_resources.py — do not edit.\n"
    "from __future__ import annotations\n"
)


URL_PARAM_RE = re.compile(r"^\{([a-zA-Z_][a-zA-Z0-9_]*)\}$")


# URL-trailing segments that represent an *action* on the parent resource
# rather than a sub-resource. For an op whose URL ends in one of these and
# whose op_method begins with the same verb (e.g. ``cancel_batch`` at
# ``/v1/batches/{batch_id}/cancel``), the generator drops the trailing
# segment so the method is emitted on the parent class — matching the
# idiomatic ``client.batches.cancel(batch_id)`` surface rather than the
# clunky ``client.batches.cancel.cancel(batch_id)``.
_ACTION_VERBS = frozenset({"cancel"})


def _split_url(url: str) -> Tuple[Tuple[str, ...], Tuple[str, ...]]:
    """Split a spec URL into ``(non-param segments, path params)``.

    Drops a leading ``/v1`` or ``/api/v1`` prefix.  Returns ``((), ())`` when
    the URL is not a standard public route (e.g. internal helpers that PUT to
    a placeholder like ``/<upload_url>`` — these are callable directly on the
    raw operations group but are intentionally *not* surfaced on the public
    resource tree).
    """
    parts = [p for p in url.split("/") if p]
    while parts:
        if parts[0] == "api" and len(parts) >= 2 and parts[1] == "v1":
            parts = parts[2:]
        elif parts[0] == "v1":
            parts = parts[1:]
        else:
            break
    if not parts:
        return (), ()
    if any("<" in p or ">" in p for p in parts):
        return (), ()
    segments: List[str] = []
    params: List[str] = []
    for part in parts:
        match = URL_PARAM_RE.match(part)
        if match:
            params.append(match.group(1))
        else:
            segments.append(re.sub(r"[^a-zA-Z0-9_]", "_", part))
    return tuple(segments), tuple(params)


def _parse_builders(path: Path) -> List[Tuple[str, str, str]]:
    lines = path.read_text(encoding="utf-8").splitlines(keepends=True)
    out: List[Tuple[str, str, str]] = []
    i = 0
    n = len(lines)
    while i < n:
        m = BUILD_RE.match(lines[i])
        if not m:
            i += 1
            continue
        group, op = m.group("group"), m.group("op")
        i += 1
        block: List[str] = []
        while i < n:
            line = lines[i]
            if line.startswith("def ") or line.startswith("class "):
                break
            block.append(line)
            i += 1
        um = URL_RE.search("".join(block))
        if not um:
            raise RuntimeError(f"No _url found in build_{group}_{op}_request")
        out.append((group, op, um.group("url")))
    return out


def _client_attr(group: str) -> str:
    return "agent_inference" if group == "agent_inference" else "inference"


def _facade_methods_for(spec: "OpSpec") -> List[str]:
    """Return method names to emit for ``spec`` on its leaf class.

    First entry is the primary method whose body is generated; any
    subsequent entries are emitted as plain-assignment aliases
    (e.g. ``retrieve = get``).  Aliases are added when the op looks like a
    retrieve-by-id (``get_*`` with a trailing path parameter) so that the
    generated surface stays friendly to callers regardless of naming style.
    """
    om = spec.op_method
    has_path_param = bool(spec.path_params)
    if om == "create_image":
        return ["generate"]
    if om.startswith("list_"):
        return ["list"]
    if om.startswith("create_"):
        return ["create"]
    if om.startswith("get_"):
        if has_path_param:
            return ["get", "retrieve"]
        return ["get"]
    if om.startswith("delete_"):
        return ["delete"]
    if om.startswith("cancel_"):
        return ["cancel"]
    if om.startswith("update_"):
        return ["update"]
    if om.startswith("patch_"):
        return ["patch"]
    return [om]


def _facade_method_name(op_method: str) -> str:
    """Legacy single-name view (used by the manifest)."""
    if op_method == "create_image":
        return "generate"
    for prefix, name in (
        ("list_", "list"),
        ("create_", "create"),
        ("get_", "get"),
        ("delete_", "delete"),
        ("cancel_", "cancel"),
        ("update_", "update"),
        ("patch_", "patch"),
    ):
        if op_method.startswith(prefix):
            return name
    return op_method


def _operation_has_json_body(op_method: str) -> bool:
    if op_method.startswith("list_") or op_method.startswith("get_"):
        return False
    if op_method.startswith("delete_") or op_method.startswith("cancel_"):
        return False
    return True


def _pascal_class_name(segment: str) -> str:
    parts = re.split(r"[_\-]+", segment)
    return "".join((p[:1].upper() + p[1:].lower()) if p else "" for p in parts if p)


@dataclass(frozen=True)
class OpSpec:
    group: str
    op_method: str
    segments: Tuple[str, ...]
    path_params: Tuple[str, ...] = ()


_FACADE_HEADER_EXTRAS = (
    "from pydo.custom_extensions import (\n"
    "    _SDK_KWARGS,\n"
    "    _prepare_body,\n"
    "    _wrap,\n"
    "    _wrap_with_id_alias,\n"
    ")\n"
)


_OP_PREFIXES_WITH_IDENTIFIABLE_RESULT = (
    "create_",
    "get_",
    "update_",
    "patch_",
)


def _derive_primary_id_field(spec: OpSpec) -> Optional[str]:
    """Best-effort guess of the spec's primary identifier field name.

    Priority:
    1. Last path parameter — the most reliable signal for retrieve-by-id
       ops (``/v1/batches/{batch_id}`` ⇒ ``batch_id``).
    2. Strip the operation prefix and append ``_id`` (``create_batch`` ⇒
       ``batch_id``, ``create_batch_file`` ⇒ ``batch_file_id``).

    The resulting field is only *applied* when it is actually present on
    the response (:func:`pydo.custom_extensions._wrap_with_id_alias`
    silently skips unknown keys), so this heuristic is safe even for
    endpoints where the spec already returns a plain ``id``.
    """
    if spec.path_params:
        return spec.path_params[-1]
    for prefix in _OP_PREFIXES_WITH_IDENTIFIABLE_RESULT:
        if spec.op_method.startswith(prefix):
            resource = spec.op_method[len(prefix) :]
            if resource:
                return f"{resource}_id"
            break
    return None


def _render_leaf_method(spec: OpSpec, method_name: str, async_mode: bool) -> str:
    """Render a single method block for a leaf class."""
    ops_attr = _client_attr(spec.group)
    async_kw = "async " if async_mode else ""
    await_kw = "await " if async_mode else ""
    path_args = list(spec.path_params)

    sig_parts: List[str] = ["self"]
    for param in path_args:
        sig_parts.append(f"{param}: str")
    sig_parts.append("**kwargs: Any")
    signature = ", ".join(sig_parts)

    path_call_args = ", ".join(f"{p}={p}" for p in path_args)
    op_head = f"self._client.{ops_attr}.{spec.op_method}("

    lines: List[str] = [
        f"    {async_kw}def {method_name}(self, {signature[len('self, '):]}) -> Any:",
        f'        """Delegates to ``client.{ops_attr}.{spec.op_method}``."""',
    ]

    primary_id = _derive_primary_id_field(spec)

    if _operation_has_json_body(spec.op_method):
        lines.extend(
            [
                "        body = {k: v for k, v in kwargs.items() "
                "if k not in _SDK_KWARGS}",
                "        sdk = {k: v for k, v in kwargs.items() "
                "if k in _SDK_KWARGS}",
                f"        body = _prepare_body({spec.op_method!r}, body)",
            ]
        )
        if path_call_args:
            call = f"{op_head}{path_call_args}, body, **sdk)"
        else:
            call = f"{op_head}body, **sdk)"
        if primary_id:
            lines.append(
                f"        return _wrap_with_id_alias("
                f"{await_kw}{call}, "
                f"primary_id_field={primary_id!r})"
            )
        else:
            lines.append(f"        return _wrap({await_kw}{call})")
    else:
        if path_call_args:
            call = f"{op_head}{path_call_args}, **kwargs)"
        else:
            call = f"{op_head}**kwargs)"
        if spec.op_method.startswith("get_") and primary_id:
            lines.append(
                f"        return _wrap_with_id_alias("
                f"{await_kw}{call}, "
                f"primary_id_field={primary_id!r})"
            )
        else:
            lines.append(f"        return _wrap({await_kw}{call})")
    return "\n".join(lines)


def _render_leaf_class_body(
    class_name: str,
    specs: List[OpSpec],
    child_segments: List[str],
    async_mode: bool,
) -> str:
    """Render the full ``class ...:`` block for a leaf / leaf+namespace class."""
    lines: List[str] = [
        f"class {class_name}:",
        '    """Inference resource helper (generated)."""',
        "",
        "    def __init__(self, client: Client) -> None:",
        "        self._client = client",
    ]
    for seg in child_segments:
        cls = _pascal_class_name(seg)
        lines.append(f"        self.{seg} = {cls}(client)")
    lines.append("")

    for spec in specs:
        method_names = _facade_methods_for(spec)
        primary, *aliases = method_names
        lines.append(_render_leaf_method(spec, primary, async_mode))
        for alias in aliases:
            lines.append(f"    {alias} = {primary}")
        lines.append("")
    return "\n".join(lines)


def _write_leaf_module(
    path: Path,
    specs: List[OpSpec],
    *,
    class_name: str,
    async_mode: bool,
) -> None:
    """Emit a standalone leaf module (no child namespaces)."""
    text = (
        _header(async_mode=async_mode)
        + _FACADE_HEADER_EXTRAS
        + "\n\n"
        + _render_leaf_class_body(class_name, specs, [], async_mode)
        + "\n"
    )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def _write_async_invoke_leaf_class(
    path: Path,
    *,
    group: str,
    async_mode: bool,
) -> None:
    """Emit ``AsyncInvoke`` with ``.images`` / ``.audio`` helpers."""
    ops = _client_attr(group)
    op_method = "create_async_invoke"
    sdk_set = ", ".join(repr(x) for x in sorted(_SDK_KWARGS))
    if async_mode:
        create_body = f"""        body = {{k: v for k, v in kwargs.items() if k not in _SDK_KWARGS}}
        sdk = {{k: v for k, v in kwargs.items() if k in _SDK_KWARGS}}
        return _wrap(await self._client.{ops}.{op_method}(body, **sdk))"""
        async_kw = "async "
        await_kw = "await "
    else:
        create_body = f"""        body = {{k: v for k, v in kwargs.items() if k not in _SDK_KWARGS}}
        sdk = {{k: v for k, v in kwargs.items() if k in _SDK_KWARGS}}
        return _wrap(self._client.{ops}.{op_method}(body, **sdk))"""
        async_kw = ""
        await_kw = ""

    text = (
        _header(async_mode=async_mode)
        + "from pydo.custom_extensions import _wrap\n"
        + "\n"
        + f"_SDK_KWARGS = frozenset({{{sdk_set}}})\n"
        + "\n\n"
        + "class AsyncInvokeImages:\n"
        + '    """Async image generation helper."""\n'
        + "\n"
        + '    def __init__(self, parent: "AsyncInvoke") -> None:\n'
        + "        self._parent = parent\n"
        + "\n"
        + f"    {async_kw}def generate(\n"
        + "        self,\n"
        + "        *,\n"
        + "        prompt: str,\n"
        + "        model_id: str,\n"
        + "        tags: Any = None,\n"
        + "        **kwargs: Any,\n"
        + "    ) -> Any:\n"
        + '        """Generate an image — maps to ``model_id`` and ``input.prompt``."""\n'
        + "        sdk = {k: v for k, v in kwargs.items() if k in _SDK_KWARGS}\n"
        + "        rest = {k: v for k, v in kwargs.items() if k not in _SDK_KWARGS}\n"
        + '        inp = {**rest, "prompt": prompt}\n'
        + '        payload = {"model_id": model_id, "input": inp}\n'
        + "        if tags is not None:\n"
        + '            payload["tags"] = tags\n'
        + f"        return {await_kw}self._parent.create(**payload, **sdk)\n"
        + "\n\n"
        + "class AsyncInvokeSpeech:\n"
        + '    """Text-to-speech helper."""\n'
        + "\n"
        + '    def __init__(self, parent: "AsyncInvoke") -> None:\n'
        + "        self._parent = parent\n"
        + "\n"
        + f"    {async_kw}def create(\n"
        + "        self,\n"
        + "        *,\n"
        + "        input: str,\n"
        + "        model_id: str,\n"
        + "        tags: Any = None,\n"
        + "        **kwargs: Any,\n"
        + "    ) -> Any:\n"
        + '        """Create speech from text — maps ``input`` to ``input.text``."""\n'
        + "        sdk = {k: v for k, v in kwargs.items() if k in _SDK_KWARGS}\n"
        + "        rest = {k: v for k, v in kwargs.items() if k not in _SDK_KWARGS}\n"
        + '        inp = {**rest, "text": input}\n'
        + '        payload = {"model_id": model_id, "input": inp}\n'
        + "        if tags is not None:\n"
        + '            payload["tags"] = tags\n'
        + f"        return {await_kw}self._parent.create(**payload, **sdk)\n"
        + "\n\n"
        + "class AsyncInvokeAudio:\n"
        + '    """Audio namespace (generation + ``speech`` for TTS)."""\n'
        + "\n"
        + '    def __init__(self, parent: "AsyncInvoke") -> None:\n'
        + "        self._root = parent\n"
        + "        self.speech = AsyncInvokeSpeech(parent)\n"
        + "\n"
        + f"    {async_kw}def generate(\n"
        + "        self,\n"
        + "        *,\n"
        + "        prompt: str,\n"
        + "        model_id: str,\n"
        + "        seconds_total: Any = None,\n"
        + "        tags: Any = None,\n"
        + "        **kwargs: Any,\n"
        + "    ) -> Any:\n"
        + '        """Async music / text-to-audio (``input.prompt``, ``seconds_total``, …)."""\n'
        + "        sdk = {k: v for k, v in kwargs.items() if k in _SDK_KWARGS}\n"
        + "        rest = {k: v for k, v in kwargs.items() if k not in _SDK_KWARGS}\n"
        + '        inp = {**rest, "prompt": prompt}\n'
        + "        if seconds_total is not None:\n"
        + '            inp["seconds_total"] = seconds_total\n'
        + '        payload = {"model_id": model_id, "input": inp}\n'
        + "        if tags is not None:\n"
        + '            payload["tags"] = tags\n'
        + f"        return {await_kw}self._root.create(**payload, **sdk)\n"
        + "\n\n"
        + "class AsyncInvoke:\n"
        + '    """Inference resource helper with nested async helpers."""\n'
        + "\n"
        + "    def __init__(self, client: Client) -> None:\n"
        + "        self._client = client\n"
        + "        self.images = AsyncInvokeImages(self)\n"
        + "        self.audio = AsyncInvokeAudio(self)\n"
        + "\n"
        + f"    {async_kw}def create(self, **kwargs: Any) -> Any:\n"
        + f'        """Delegates to ``client.{ops}.{op_method}``."""\n'
        + create_body
        + "\n"
    )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def _immediate_child_segments(
    prefix: Tuple[str, ...], tree_keys: Set[Tuple[str, ...]]
) -> List[str]:
    plen = len(prefix)
    kids: Set[str] = set()
    for k in tree_keys:
        if len(k) == plen + 1 and k[:plen] == prefix:
            kids.add(k[-1])
    return sorted(kids)


def _write_namespace_init(
    init_path: Path,
    prefix: Tuple[str, ...],
    children: List[str],
    *,
    async_mode: bool,
) -> None:
    parent_seg = prefix[-1]
    parent_class = _pascal_class_name(parent_seg)
    imp = "from pydo.aio import Client" if async_mode else "from pydo import Client"
    needs_generate_alias = parent_seg == "images" and "generations" in children
    lines = [
        INIT_HEADER,
        "",
        imp,
    ]
    if needs_generate_alias:
        lines.append("from typing import Any")
    for c in children:
        lines.append(f"from .{c} import {_pascal_class_name(c)}")
    lines.extend(
        [
            "",
            "",
            f"class {parent_class}:",
            '    """Inference path namespace (generated)."""',
            "",
            "    def __init__(self, client: Client) -> None:",
        ]
    )
    for c in children:
        cc = _pascal_class_name(c)
        lines.append(f"        self.{c} = {cc}(client)")
    if needs_generate_alias:
        async_kw = "async " if async_mode else ""
        ret_kw = "await " if async_mode else ""
        lines.append("")
        lines.append(f"    {async_kw}def generate(self, **kwargs: Any) -> Any:")
        lines.append(
            '        """Alias for ``images.generations.generate`` '
            '(``POST /v1/images/generations``)."""'
        )
        lines.append(f"        return {ret_kw}self.generations.generate(**kwargs)\n")
    lines.append("")
    lines.append(f'__all__ = ["{parent_class}"]')
    lines.append("")
    init_path.write_text("\n".join(lines), encoding="utf-8")


def _normalize_action_segments(
    segments: Tuple[str, ...], op_method: str
) -> Tuple[str, ...]:
    """Drop a trailing action-verb segment when it aligns with ``op_method``.

    Example: ``segments=('batches', 'cancel')`` with ``op_method='cancel_batch'``
    becomes ``('batches',)`` so the op is emitted as a method on the parent
    namespace.
    """
    if len(segments) >= 2 and segments[-1] in _ACTION_VERBS:
        if op_method.startswith(f"{segments[-1]}_"):
            return segments[:-1]
    return segments


def _collect_ops_by_group(
    builders: List[Tuple[str, str, str]],
) -> Dict[str, List[OpSpec]]:
    by_group: Dict[str, List[OpSpec]] = {}
    for group, op_method, url in builders:
        segs, params = _split_url(url)
        if not segs:
            # Internal helper (e.g. presigned-URL PUT) — still reachable via
            # ``client.inference.<op_method>`` directly, just not placed on
            # the public resource tree.
            continue
        segs = _normalize_action_segments(segs, op_method)
        by_group.setdefault(group, []).append(
            OpSpec(
                group=group,
                op_method=op_method,
                segments=segs,
                path_params=params,
            )
        )
    return by_group


def _build_tree_keys(specs: List[OpSpec]) -> Set[Tuple[str, ...]]:
    keys: Set[Tuple[str, ...]] = set()
    for s in specs:
        for i in range(len(s.segments)):
            keys.add(tuple(s.segments[: i + 1]))
    return keys


def _write_package_init_with_facade(
    init_path: Path,
    top_segments: List[str],
    *,
    class_name: str,
    async_mode: bool,
) -> None:
    """Write package ``__init__.py`` with the top-level resource root class."""
    imp = "from pydo.aio import Client" if async_mode else "from pydo import Client"
    lines = [
        INIT_HEADER,
        "",
        imp,
    ]
    for seg in sorted(top_segments):
        cls = _pascal_class_name(seg)
        lines.append(f"from .{seg} import {cls}")
    lines.extend(
        [
            "",
            "",
            f"class {class_name}:",
            '    """Nested inference resource root (generated)."""',
            "",
            "    def __init__(self, client: Client) -> None:",
        ]
    )
    for seg in sorted(top_segments):
        cls = _pascal_class_name(seg)
        lines.append(f"        self.{seg} = {cls}(client)")
    lines.append("")
    lines.append(f'__all__ = ["{class_name}"]')
    lines.append("")
    init_path.write_text("\n".join(lines), encoding="utf-8")


def _write_empty_package_init(base: Path, *, class_name: str, async_mode: bool) -> None:
    base.mkdir(parents=True, exist_ok=True)
    imp = "from pydo.aio import Client" if async_mode else "from pydo import Client"
    (base / "__init__.py").write_text(
        INIT_HEADER
        + "\n"
        + f"{imp}\n"
        + "\n\n"
        + f"class {class_name}:\n"
        + '    """Nested inference resource root (no operations in spec)."""\n'
        + "\n"
        + "    def __init__(self, client: Client) -> None:\n"
        + "        self._client = client\n"
        + "\n"
        + f'__all__ = ["{class_name}"]\n',
        encoding="utf-8",
    )


_FILES_FACADE_DRIVER_OPS = ("create_batch_file", "get_batch_results")
_FILES_FACADE_OPTIONAL_OPS = ("delete_batch_file",)


def _files_facade_driver_ops_present(specs: List[OpSpec]) -> bool:
    op_names = {spec.op_method for spec in specs}
    return all(op in op_names for op in _FILES_FACADE_DRIVER_OPS)


def _files_facade_optional_op_present(specs: List[OpSpec], op: str) -> bool:
    return any(spec.op_method == op for spec in specs)


def _write_files_facade_module(
    path: Path, specs: List[OpSpec], *, async_mode: bool
) -> None:
    """Emit the cross-resource ``files`` facade module.

    The methods compose two spec operations behind a single, ergonomic
    surface: ``create`` combines ``create_batch_file`` (intent) with the PUT
    upload to the returned presigned URL, and ``content`` wraps the result
    of ``get_batch_results`` so downloaded bytes can be consumed eagerly.

    The module is only emitted when both driver ops are present in the
    current generation, so existing resource trees remain unaffected when
    the spec does not define batch file operations.
    """
    client_import = (
        "from pydo.aio import Client" if async_mode else "from pydo import Client"
    )
    async_kw = "async " if async_mode else ""
    await_kw = "await " if async_mode else ""
    upload_call = (
        "await asyncio.to_thread(_upload_via_presigned, intent['upload_url'], "
        "data, content_type)"
        if async_mode
        else "_upload_via_presigned(intent['upload_url'], data, content_type)"
    )
    asyncio_import = "import asyncio\n" if async_mode else ""

    body = f'''{INIT_HEADER}
{asyncio_import}from typing import Any

{client_import}
from pydo.custom_extensions import (
    _SDK_KWARGS,
    _FileContent,
    _read_file_arg,
    _upload_via_presigned,
    _wrap,
    _wrap_file_content,
)


class Files:
    """Convenience facade for JSONL input upload and output download."""

    def __init__(self, client: Client) -> None:
        self._client = client

    {async_kw}def create(
        self,
        *,
        file: Any = None,
        purpose: str = "batch",
        **kwargs: Any,
    ) -> Any:
        """Upload a JSONL input file for use with ``batches.create``.

        Combines two spec operations: creating a file intent
        (``POST /v1/batches/files``) and uploading bytes to the returned
        presigned URL.  Returns an object exposing both the canonical
        spec fields (``file_id``, ``upload_url``, ``expires_at``) and an
        ``id`` alias.

        :keyword file: File content; accepts a filesystem path, raw bytes,
            a readable stream, or a ``(name, data)`` tuple. Required.
        :keyword purpose: Free-form label retained on the returned object
            (``"batch"`` is the only purpose currently used server-side).
        """
        name, data, content_type = _read_file_arg(file)
        sdk = {{k: v for k, v in kwargs.items() if k in _SDK_KWARGS}}
        intent = {await_kw}self._client.inference.create_batch_file(
            {{"file_name": name}}, **sdk
        )
        {upload_call}
        result = dict(intent)
        result["id"] = result.get("file_id")
        result["purpose"] = purpose
        result["filename"] = name
        result["bytes"] = len(data)
        return _wrap(result)

    {async_kw}def content(self, file_id: str, **kwargs: Any) -> _FileContent:
        """Fetch the output of a completed batch job.

        ``file_id`` may be the value read from ``batch.output_file_id`` on
        a completed batch.  Delegates to ``get_batch_results`` and returns
        a response object whose ``.read()`` / ``.text`` accessors lazily
        download the referenced presigned URL.
        """
        response = {await_kw}self._client.inference.get_batch_results(
            batch_id=file_id, **kwargs
        )
        return _wrap_file_content(response)
'''

    if _files_facade_optional_op_present(specs, "delete_batch_file"):
        body += f'''
    {async_kw}def delete(self, file_id: str, **kwargs: Any) -> Any:
        """Delete a previously uploaded batch input file.

        Delegates to ``delete_batch_file`` (``DELETE /v1/batches/files/{{file_id}}``).
        """
        return _wrap(
            {await_kw}self._client.inference.delete_batch_file(
                file_id=file_id, **kwargs
            )
        )
'''

    body += """

__all__ = ["Files"]
"""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(body, encoding="utf-8")


def _write_combined_package_init(
    init_path: Path,
    prefix: Tuple[str, ...],
    specs: List[OpSpec],
    child_segments: List[str],
    *,
    async_mode: bool,
) -> None:
    """Emit ``__init__.py`` for a prefix that is BOTH a leaf and a namespace.

    Example: ``/v1/batches`` has its own create/get operations **and** nested
    routes like ``/v1/batches/files`` and ``/v1/batches/{id}/result``.
    """
    parent_class = _pascal_class_name(prefix[-1])
    client_import = (
        "from pydo.aio import Client" if async_mode else "from pydo import Client"
    )
    lines: List[str] = [
        INIT_HEADER,
        "",
        "from typing import Any",
        "",
        client_import,
        "from pydo.custom_extensions import (",
        "    _SDK_KWARGS,",
        "    _prepare_body,",
        "    _wrap,",
        "    _wrap_with_id_alias,",
        ")",
    ]
    for child in child_segments:
        lines.append(f"from .{child} import {_pascal_class_name(child)}")
    lines.append("")
    lines.append("")
    lines.append(
        _render_leaf_class_body(parent_class, specs, child_segments, async_mode)
    )
    lines.append("")
    lines.append(f'__all__ = ["{parent_class}"]')
    lines.append("")
    init_path.parent.mkdir(parents=True, exist_ok=True)
    init_path.write_text("\n".join(lines), encoding="utf-8")


def _emit_group(
    base: Path,
    specs: List[OpSpec],
    *,
    facade_class: str,
    async_mode: bool,
) -> List[str]:
    """Return sorted top-level URL segments (first path component after ``/v1``)."""
    if not specs:
        _write_empty_package_init(base, class_name=facade_class, async_mode=async_mode)
        return []

    leaves_by_prefix: Dict[Tuple[str, ...], List[OpSpec]] = {}
    for spec in specs:
        leaves_by_prefix.setdefault(tuple(spec.segments), []).append(spec)

    tree_keys = _build_tree_keys(specs)

    for prefix in sorted(tree_keys, key=len):
        leaf_specs = leaves_by_prefix.get(prefix, [])
        child_segments = _immediate_child_segments(prefix, tree_keys)
        *parents, leaf_seg = prefix
        leaf_class = _pascal_class_name(leaf_seg)

        is_special_async_invoke = (
            len(prefix) == 1
            and leaf_seg == "async_invoke"
            and leaf_specs
            and leaf_specs[0].op_method == "create_async_invoke"
        )

        if is_special_async_invoke:
            rel = (
                Path(f"{leaf_seg}.py")
                if not parents
                else Path(*parents) / f"{leaf_seg}.py"
            )
            _write_async_invoke_leaf_class(
                base / rel,
                group=leaf_specs[0].group,
                async_mode=async_mode,
            )
            continue

        if leaf_specs and not child_segments:
            rel = (
                Path(f"{leaf_seg}.py")
                if not parents
                else Path(*parents) / f"{leaf_seg}.py"
            )
            _write_leaf_module(
                base / rel,
                leaf_specs,
                class_name=leaf_class,
                async_mode=async_mode,
            )
        elif leaf_specs and child_segments:
            init_dir = base.joinpath(*prefix)
            init_dir.mkdir(parents=True, exist_ok=True)
            _write_combined_package_init(
                init_dir / "__init__.py",
                prefix,
                leaf_specs,
                child_segments,
                async_mode=async_mode,
            )
        elif child_segments:
            init_dir = base.joinpath(*prefix)
            init_dir.mkdir(parents=True, exist_ok=True)
            _write_namespace_init(
                init_dir / "__init__.py",
                prefix,
                child_segments,
                async_mode=async_mode,
            )

    top_segments = sorted({s.segments[0] for s in specs})

    if _files_facade_driver_ops_present(specs):
        _write_files_facade_module(base / "files.py", specs, async_mode=async_mode)
        if "files" not in top_segments:
            top_segments.append("files")
            top_segments.sort()

    _write_package_init_with_facade(
        base / "__init__.py",
        top_segments,
        class_name=facade_class,
        async_mode=async_mode,
    )
    return top_segments


def _write_client_surface(
    path: Path,
    inference_top_segments: List[str],
) -> None:
    """Emit mixin classes merged into :class:`pydo.Client` (sync and async both use this file)."""
    lines: List[str] = [
        INIT_HEADER,
        "",
        "from typing import Any",
        "",
        "",
        "class InferenceClientSurface:",
        '    """Generated shortcuts for serverless inference (discovered from the published spec)."""',
        "",
    ]
    # ``images`` is handled manually in Client.__init__ (reassigned after
    # GeneratedClient sets self.images = ImagesOperations).  A @property
    # would block that assignment since it has no setter.
    skip_surface_segments = frozenset({"images"})

    for seg in inference_top_segments:
        if not seg.isidentifier() or seg in skip_surface_segments:
            continue
        lines.append("    @property")
        lines.append(f"    def {seg}(self) -> Any:")
        lines.append(
            f'        """Nested serverless inference API under path segment ``{seg}``."""\n'
        )
        lines.append(f"        return self._require_inference_resource_root().{seg}\n")
    if "async_invoke" in inference_top_segments:
        lines.append("    @property")
        lines.append("    def audio(self) -> Any:")
        lines.append(
            '        """Audio namespace (TTS + generation via async-invoke)."""\n'
        )
        lines.append(
            "        return self._require_inference_resource_root().async_invoke.audio\n"
        )
        lines.append("    @property")
        lines.append("    def speech(self) -> Any:")
        lines.append(
            '        """TTS entry: same as ``audio.speech`` (async-invoke)."""\n'
        )
        lines.append(
            "        return self._require_inference_resource_root().async_invoke.audio.speech\n"
        )
        lines.append("    @property")
        lines.append("    def async_images(self) -> Any:")
        lines.append(
            '        """Async image generation: same as ``async_invoke.images``."""\n'
        )
        lines.append(
            "        return self._require_inference_resource_root().async_invoke.images\n"
        )
    lines.append("    @property")
    lines.append("    def inference_layout(self) -> Any:")
    lines.append(
        '        """Full nested serverless inference layout (same objects as the shortcuts above)."""\n'
    )
    lines.append("        return self._require_inference_resource_root()\n")
    lines.extend(
        [
            "",
            "",
            "class AgentClientSurface:",
            '    """Generated shortcut for agent inference operations."""',
            "",
            "    @property",
            "    def agent(self) -> Any:",
            '        """Nested agent inference API (``agent_inference`` operation group)."""\n',
            "        return self._require_agent_inference_resource_root()",
            "",
            "",
            '__all__ = ["AgentClientSurface", "InferenceClientSurface"]',
            "",
        ]
    )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")


def _write_inference_surface_manifest(
    path: Path,
    by_group: Dict[str, List[OpSpec]],
) -> None:
    """Machine-readable list of discovered inference operations (for docs / tooling)."""
    payload: Dict[str, Any] = {
        "source": "operations/_operations.py build_inference_* / build_agent_inference_*",
        "inference": [],
        "agent_inference": [],
    }
    for spec in by_group.get("inference", []):
        payload["inference"].append(
            {
                "op_method": spec.op_method,
                "path_segments": list(spec.segments),
                "path_params": list(spec.path_params),
                "facade_methods": _facade_methods_for(spec),
            }
        )
    for spec in by_group.get("agent_inference", []):
        payload["agent_inference"].append(
            {
                "op_method": spec.op_method,
                "path_segments": list(spec.segments),
                "path_params": list(spec.path_params),
                "facade_methods": _facade_methods_for(spec),
            }
        )
    path.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")


_NAMESPACE_HEADER = (
    "# ------------------------------------\n"
    "# Copyright (c) DigitalOcean.\n"
    "# Licensed under the Apache-2.0 License.\n"
    "# ------------------------------------\n"
    "# Generated by scripts/generate_inference_resources.py — do not edit.\n"
)


def _render_namespace_client(
    *,
    namespaces: List[str],
    async_mode: bool,
) -> str:
    """Render the ``pydo.inference[.aio].Client`` shim.

    The list of ``namespaces`` is the union of spec-discovered inference
    top-level segments and the cross-resource shortcuts the generator
    attaches to :class:`InferenceClientSurface` / :class:`AgentClientSurface`.
    """
    base_module = "pydo.aio" if async_mode else "pydo"
    repr_label = "pydo.inference.aio.Client" if async_mode else "pydo.inference.Client"
    docstring_title = (
        (
            '"""Async inference-focused entry point: ``from pydo.inference.aio import Client``.\n\n'
            "Asynchronous twin of :class:`pydo.inference.Client`. Same surface,\n"
            "``await``-friendly. See :mod:`pydo.inference` for usage details.\n"
            '"""\n'
        )
        if async_mode
        else (
            '"""Inference-focused entry point: ``from pydo.inference import Client``.\n\n'
            "This namespace gives serverless-inference and agent-inference callers a\n"
            "purpose-built ``Client`` that mirrors the conventions used by other\n"
            "LLM SDKs (``Client(token=...)`` / ``Client(api_key=...)``) while staying\n"
            "fully integrated with :mod:`pydo` — the same authentication, transport\n"
            "pipeline, retry, logging and response wrappers are reused under the hood.\n\n"
            "The list of top-level namespaces exposed on this client\n"
            "(``chat``, ``models``, ``embeddings``, ``images``, ``responses``,\n"
            "``batches``, ``audio``, ``speech``, ``files``, ``agent`` …) is derived\n"
            "from the OpenAPI spec at code-generation time, so any inference endpoint\n"
            "added to the spec in the future surfaces here automatically — no manual\n"
            "edits to this module are required.\n\n"
            "Example::\n\n"
            "    import os\n"
            "    from pydo.inference import Client\n\n"
            '    client = Client(token=os.environ["DIGITALOCEAN_TOKEN"])\n\n'
            "    resp = client.chat.completions.create(\n"
            '        model="llama3.3-70b-instruct",\n'
            '        messages=[{"role": "user", "content": "Hello!"}],\n'
            "    )\n"
            '"""\n'
        )
    )
    class_doc = (
        (
            '    """Inference-focused DigitalOcean async client.\n\n'
            "    Asynchronous counterpart to :class:`pydo.inference.Client`. Every\n"
            "    inference / agent-inference surface is exposed as an awaitable\n"
            "    method, while the underlying :class:`pydo.aio.Client` machinery\n"
            "    (authentication, transport pipeline, multi-base-URL routing, SSE\n"
            "    streaming) is reused unchanged.\n"
            '    """\n'
        )
        if async_mode
        else (
            '    """Inference-focused DigitalOcean Python client.\n\n'
            "    A drop-in entry point under ``pydo.inference`` for callers whose\n"
            "    workload is serverless inference (chat completions, embeddings,\n"
            "    image / audio generation, batch inference, agent inference, …).\n\n"
            "    Inherits the full :class:`pydo.Client` machinery — authentication,\n"
            "    transport pipeline, multi-base-URL routing and SSE streaming — so\n"
            "    every inference surface that works on ``pydo.Client`` also works\n"
            "    here. The top-level attribute surface, however, is narrowed to the\n"
            "    inference and agent-inference namespaces so editor autocomplete\n"
            "    (and ``dir(client)``) stay focused on inference primitives.\n"
            '    """\n'
        )
    )

    namespaces_literal = (
        "(\n" + "".join(f"    {name!r},\n" for name in namespaces) + ")"
    )

    return (
        _NAMESPACE_HEADER
        + docstring_title
        + "from __future__ import annotations\n\n"
        + "from typing import List, Optional\n\n"
        + f"from {base_module} import Client as _DigitalOceanClient\n"
        + f"from {base_module}._patch import TokenCredentials\n"
        + "from pydo.custom_extensions import INFERENCE_BASE_URL\n\n\n"
        + "# Top-level attributes that the namespaced ``Client`` advertises via\n"
        + "# ``dir()``. Populated by ``scripts/generate_inference_resources.py``\n"
        + "# from the discovered OpenAPI surface plus cross-resource shortcuts.\n"
        + f"_INFERENCE_NAMESPACES: tuple = {namespaces_literal}\n\n\n"
        + "class Client(_DigitalOceanClient):\n"
        + class_doc
        + "\n"
        + "    def __init__(\n"
        + "        self,\n"
        + "        token: Optional[str] = None,\n"
        + "        *,\n"
        + "        api_key: Optional[str] = None,\n"
        + "        timeout: int = 120,\n"
        + "        inference_endpoint: str = INFERENCE_BASE_URL,\n"
        + '        agent_endpoint: str = "",\n'
        + "        **kwargs,\n"
        + "    ) -> None:\n"
        + "        super().__init__(\n"
        + "            token=token,\n"
        + "            api_key=api_key,\n"
        + "            timeout=timeout,\n"
        + "            inference_endpoint=inference_endpoint,\n"
        + "            agent_endpoint=agent_endpoint,\n"
        + "            **kwargs,\n"
        + "        )\n\n"
        + "    def __dir__(self) -> List[str]:\n"
        + "        return sorted(set(_INFERENCE_NAMESPACES))\n\n"
        + "    def __repr__(self) -> str:\n"
        + f'        return "<{repr_label}>"\n\n\n'
        + '__all__ = ["Client", "TokenCredentials"]\n'
    )


def _discover_namespaces(
    inference_top_segments: List[str], agent_top_segments: List[str]
) -> List[str]:
    """Compute the union of top-level segments + cross-resource shortcuts.

    ``images`` is intentionally included even though the surface mixin
    skips it — :class:`pydo.Client` re-attaches inference ``generate`` /
    ``generations`` onto the v2 ``images`` object, so ``client.images``
    is still a valid inference entry point on this namespace.
    """
    discovered = set(inference_top_segments)
    discovered.update(_INFERENCE_SURFACE_EXTRAS)
    if agent_top_segments:
        discovered.update(_AGENT_SURFACE_EXTRAS)
    return sorted(discovered)


def _write_namespace_clients(
    inference_top_segments: List[str],
    agent_top_segments: List[str],
) -> None:
    """Emit ``src/pydo/inference/__init__.py`` and its async twin."""
    namespaces = _discover_namespaces(inference_top_segments, agent_top_segments)

    NAMESPACE_ROOT.mkdir(parents=True, exist_ok=True)
    (NAMESPACE_ROOT / "__init__.py").write_text(
        _render_namespace_client(namespaces=namespaces, async_mode=False),
        encoding="utf-8",
    )

    aio_dir = NAMESPACE_ROOT / "aio"
    aio_dir.mkdir(parents=True, exist_ok=True)
    (aio_dir / "__init__.py").write_text(
        _render_namespace_client(namespaces=namespaces, async_mode=True),
        encoding="utf-8",
    )


def main() -> None:
    if not OPS_PATH.is_file():
        raise SystemExit(f"missing {OPS_PATH}")

    if OUT_ROOT.exists():
        shutil.rmtree(OUT_ROOT)

    builders = _parse_builders(OPS_PATH)
    by_group = _collect_ops_by_group(builders)

    OUT_ROOT.mkdir(parents=True, exist_ok=True)

    inference_top = _emit_group(
        OUT_ROOT / "inference",
        by_group.get("inference", []),
        facade_class="InferenceResources",
        async_mode=False,
    )
    agent_top = _emit_group(
        OUT_ROOT / "agent_inference",
        by_group.get("agent_inference", []),
        facade_class="AgentInferenceResources",
        async_mode=False,
    )
    _write_client_surface(OUT_ROOT / "client_surface.py", inference_top)
    _write_inference_surface_manifest(OUT_ROOT / "inference_surface.json", by_group)
    _write_namespace_clients(inference_top, agent_top)

    aio_root = OUT_ROOT / "aio"
    aio_root.mkdir(parents=True, exist_ok=True)
    _emit_group(
        aio_root / "inference",
        by_group.get("inference", []),
        facade_class="InferenceResources",
        async_mode=True,
    )
    _emit_group(
        aio_root / "agent_inference",
        by_group.get("agent_inference", []),
        facade_class="AgentInferenceResources",
        async_mode=True,
    )
    (aio_root / "__init__.py").write_text(
        INIT_HEADER
        + '\n"""Async inference resource packages (e.g. ``pydo.resources.aio.inference``)."""\n'
        "\n"
        "__all__ = []\n",
        encoding="utf-8",
    )

    (OUT_ROOT / "__init__.py").write_text(
        INIT_HEADER
        + '\n"""Nested inference packages: ``inference/``, ``agent_inference/``, ``aio/``."""\n'
        "\n"
        "__all__ = []\n",
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
