#!/usr/bin/env python3
# ------------------------------------
# Copyright (c) DigitalOcean.
# Licensed under the Apache-2.0 License.
# ------------------------------------
"""Emit nested ``src/pydo/resources/`` packages for inference HTTP paths.

**Source of truth:** only ``build_inference_*`` / ``build_agent_inference_*``
helpers in ``operations/_operations.py`` (Autorest output from the OpenAPI
spec).  Droplet / v2 APIs are not read here.

For each inference URL, path segments become nested modules/classes; method
names map from operation names (``list_*`` → ``list``, ``create_image`` →
``generate``, etc.).  Keyword arguments on generated helpers are passed into
the JSON body (except SDK kwargs like ``headers``, ``cls``), matching the
schema Autorest embedded for each operation.

Also emits ``client_surface*.py`` mixins so :class:`pydo.Client` shortcuts
(``chat``, ``models``, ``inference_layout``, ``agent``, …) track whatever the
spec contains — no hand-maintained list in ``_patch.py``.

Shortcuts on :class:`pydo.Client`: use ``client.image_generations`` (or
``client.inference_layout.images``) for ``POST /v1/images/generations`` — we do **not**
expose ``client.images`` for inference because that name is reserved for the DO v2 Images
API. ``client.audio`` / ``client.speech`` / ``client.async_images`` mirror familiar
paths; ``async_invoke`` still exposes ``.images`` / ``.audio`` under the layout.

Run after Autorest (``make generate``).
"""
from __future__ import annotations

import json
import re
import shutil
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, List, Set, Tuple

ROOT = Path(__file__).resolve().parents[1]
OPS_PATH = ROOT / "src/pydo/operations/_operations.py"
OUT_ROOT = ROOT / "src/pydo/resources"

BUILD_RE = re.compile(
    r"^def build_(?P<group>inference|agent_inference)_(?P<op>.+)_request\b"
)
URL_RE = re.compile(r'_url\s*=\s*["\'](?P<url>[^"\']+)["\']')

_SDK_KWARGS = frozenset(
    {
        "headers",
        "params",
        "content_type",
        "cls",
        "raw_request_hook",
        "raw_response_hook",
        "polling",
        "continuation_token",
        "form_content_type",
        "error_map",
    }
)


def _header(*, async_mode: bool) -> str:
    client_import = (
        "from pydo.aio import Client" if async_mode else "from pydo import Client"
    )
    return (
        "# ------------------------------------\n"
        "# Copyright (c) DigitalOcean.\n"
        "# Licensed under the Apache-2.0 License.\n"
        "# ------------------------------------\n"
        "# Generated by scripts/generate_inference_resources.py — do not edit.\n"
        "from __future__ import annotations\n"
        "\n"
        "from typing import Any\n"
        "\n"
        f"{client_import}\n"
        "from pydo.custom_extensions import _wrap\n"
    )


INIT_HEADER = (
    "# ------------------------------------\n"
    "# Copyright (c) DigitalOcean.\n"
    "# Licensed under the Apache-2.0 License.\n"
    "# ------------------------------------\n"
    "# Generated by scripts/generate_inference_resources.py — do not edit.\n"
    "from __future__ import annotations\n"
)


def _path_segments(url: str) -> List[str]:
    parts = [p for p in url.split("/") if p]
    while parts:
        if parts[0] == "api" and len(parts) >= 2 and parts[1] == "v1":
            parts = parts[2:]
        elif parts[0] == "v1":
            parts = parts[1:]
        else:
            break
    return [re.sub(r"[^a-zA-Z0-9_]", "_", s) for s in parts]


def _parse_builders(path: Path) -> List[Tuple[str, str, str]]:
    lines = path.read_text(encoding="utf-8").splitlines(keepends=True)
    out: List[Tuple[str, str, str]] = []
    i = 0
    n = len(lines)
    while i < n:
        m = BUILD_RE.match(lines[i])
        if not m:
            i += 1
            continue
        group, op = m.group("group"), m.group("op")
        i += 1
        block: List[str] = []
        while i < n:
            line = lines[i]
            if line.startswith("def ") or line.startswith("class "):
                break
            block.append(line)
            i += 1
        um = URL_RE.search("".join(block))
        if not um:
            raise RuntimeError(f"No _url found in build_{group}_{op}_request")
        out.append((group, op, um.group("url")))
    return out


def _client_attr(group: str) -> str:
    return "agent_inference" if group == "agent_inference" else "inference"


def _facade_method_name(op_method: str) -> str:
    if op_method == "create_image":
        return "generate"
    if op_method.startswith("list_"):
        return "list"
    if op_method.startswith("create_"):
        return "create"
    if op_method.startswith("get_"):
        return "get"
    if op_method.startswith("delete_"):
        return "delete"
    if op_method.startswith("update_"):
        return "update"
    if op_method.startswith("patch_"):
        return "patch"
    return op_method


def _operation_has_json_body(op_method: str) -> bool:
    if op_method.startswith("list_") or op_method.startswith("get_"):
        return False
    if op_method.startswith("delete_"):
        return False
    return True


def _pascal_class_name(segment: str) -> str:
    parts = re.split(r"[_\-]+", segment)
    return "".join((p[:1].upper() + p[1:].lower()) if p else "" for p in parts if p)


@dataclass(frozen=True)
class OpSpec:
    group: str
    op_method: str
    segments: List[str]


def _write_leaf_class(
    path: Path,
    *,
    group: str,
    op_method: str,
    facade_method: str,
    class_name: str,
    async_mode: bool,
) -> None:
    ops = _client_attr(group)
    sdk_set = ", ".join(repr(x) for x in sorted(_SDK_KWARGS))

    if _operation_has_json_body(op_method):
        if async_mode:
            method_body = f"""        body = {{k: v for k, v in kwargs.items() if k not in _SDK_KWARGS}}
        sdk = {{k: v for k, v in kwargs.items() if k in _SDK_KWARGS}}
        return _wrap(await self._client.{ops}.{op_method}(body, **sdk))"""
        else:
            method_body = f"""        body = {{k: v for k, v in kwargs.items() if k not in _SDK_KWARGS}}
        sdk = {{k: v for k, v in kwargs.items() if k in _SDK_KWARGS}}
        return _wrap(self._client.{ops}.{op_method}(body, **sdk))"""
    else:
        if async_mode:
            method_body = (
                f"        return _wrap(await self._client.{ops}.{op_method}(**kwargs))"
            )
        else:
            method_body = f"        return _wrap(self._client.{ops}.{op_method}(**kwargs))"

    async_kw = "async " if async_mode else ""

    text = (
        _header(async_mode=async_mode)
        + "\n"
        + f"_SDK_KWARGS = frozenset({{{sdk_set}}})\n"
        + "\n\n"
        + f"class {class_name}:\n"
        + '    """Inference resource helper (generated)."""\n'
        + "\n"
        + "    def __init__(self, client: Client) -> None:\n"
        + "        self._client = client\n"
        + "\n"
        + f"    {async_kw}def {facade_method}(self, **kwargs: Any) -> Any:\n"
        + f'        """Delegates to ``client.{ops}.{op_method}``."""\n'
        + method_body
        + "\n"
    )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def _write_async_invoke_leaf_class(
    path: Path,
    *,
    group: str,
    async_mode: bool,
) -> None:
    """Emit ``AsyncInvoke`` with ``.images`` / ``.audio`` helpers."""
    ops = _client_attr(group)
    op_method = "create_async_invoke"
    sdk_set = ", ".join(repr(x) for x in sorted(_SDK_KWARGS))
    if async_mode:
        create_body = f"""        body = {{k: v for k, v in kwargs.items() if k not in _SDK_KWARGS}}
        sdk = {{k: v for k, v in kwargs.items() if k in _SDK_KWARGS}}
        return _wrap(await self._client.{ops}.{op_method}(body, **sdk))"""
        async_kw = "async "
        await_kw = "await "
    else:
        create_body = f"""        body = {{k: v for k, v in kwargs.items() if k not in _SDK_KWARGS}}
        sdk = {{k: v for k, v in kwargs.items() if k in _SDK_KWARGS}}
        return _wrap(self._client.{ops}.{op_method}(body, **sdk))"""
        async_kw = ""
        await_kw = ""

    text = (
        _header(async_mode=async_mode)
        + "\n"
        + f"_SDK_KWARGS = frozenset({{{sdk_set}}})\n"
        + "\n\n"
        + 'class AsyncInvokeImages:\n'
        + '    """Async image generation helper."""\n'
        + "\n"
        + '    def __init__(self, parent: "AsyncInvoke") -> None:\n'
        + "        self._parent = parent\n"
        + "\n"
        + f"    {async_kw}def generate(\n"
        + "        self,\n"
        + "        *,\n"
        + "        prompt: str,\n"
        + "        model_id: str,\n"
        + "        tags: Any = None,\n"
        + "        **kwargs: Any,\n"
        + "    ) -> Any:\n"
        + '        """Generate an image — maps to ``model_id`` and ``input.prompt``."""\n'
        + "        sdk = {k: v for k, v in kwargs.items() if k in _SDK_KWARGS}\n"
        + "        rest = {k: v for k, v in kwargs.items() if k not in _SDK_KWARGS}\n"
        + '        inp = {**rest, "prompt": prompt}\n'
        + "        payload = {\"model_id\": model_id, \"input\": inp}\n"
        + "        if tags is not None:\n"
        + '            payload["tags"] = tags\n'
        + f"        return {await_kw}self._parent.create(**payload, **sdk)\n"
        + "\n\n"
        + 'class AsyncInvokeSpeech:\n'
        + '    """Text-to-speech helper."""\n'
        + "\n"
        + '    def __init__(self, parent: "AsyncInvoke") -> None:\n'
        + "        self._parent = parent\n"
        + "\n"
        + f"    {async_kw}def create(\n"
        + "        self,\n"
        + "        *,\n"
        + "        input: str,\n"
        + "        model_id: str,\n"
        + "        tags: Any = None,\n"
        + "        **kwargs: Any,\n"
        + "    ) -> Any:\n"
        + '        """Create speech from text — maps ``input`` to ``input.text``."""\n'
        + "        sdk = {k: v for k, v in kwargs.items() if k in _SDK_KWARGS}\n"
        + "        rest = {k: v for k, v in kwargs.items() if k not in _SDK_KWARGS}\n"
        + '        inp = {**rest, "text": input}\n'
        + "        payload = {\"model_id\": model_id, \"input\": inp}\n"
        + "        if tags is not None:\n"
        + '            payload["tags"] = tags\n'
        + f"        return {await_kw}self._parent.create(**payload, **sdk)\n"
        + "\n\n"
        + 'class AsyncInvokeAudio:\n'
        + '    """Audio namespace (generation + ``speech`` for TTS)."""\n'
        + "\n"
        + '    def __init__(self, parent: "AsyncInvoke") -> None:\n'
        + "        self._root = parent\n"
        + "        self.speech = AsyncInvokeSpeech(parent)\n"
        + "\n"
        + f"    {async_kw}def generate(\n"
        + "        self,\n"
        + "        *,\n"
        + "        prompt: str,\n"
        + "        model_id: str,\n"
        + "        seconds_total: Any = None,\n"
        + "        tags: Any = None,\n"
        + "        **kwargs: Any,\n"
        + "    ) -> Any:\n"
        + '        """Async music / text-to-audio (``input.prompt``, ``seconds_total``, …)."""\n'
        + "        sdk = {k: v for k, v in kwargs.items() if k in _SDK_KWARGS}\n"
        + "        rest = {k: v for k, v in kwargs.items() if k not in _SDK_KWARGS}\n"
        + '        inp = {**rest, "prompt": prompt}\n'
        + "        if seconds_total is not None:\n"
        + '            inp["seconds_total"] = seconds_total\n'
        + "        payload = {\"model_id\": model_id, \"input\": inp}\n"
        + "        if tags is not None:\n"
        + '            payload["tags"] = tags\n'
        + f"        return {await_kw}self._root.create(**payload, **sdk)\n"
        + "\n\n"
        + "class AsyncInvoke:\n"
        + '    """Inference resource helper with nested async helpers."""\n'
        + "\n"
        + "    def __init__(self, client: Client) -> None:\n"
        + "        self._client = client\n"
        + "        self.images = AsyncInvokeImages(self)\n"
        + "        self.audio = AsyncInvokeAudio(self)\n"
        + "\n"
        + f"    {async_kw}def create(self, **kwargs: Any) -> Any:\n"
        + f'        """Delegates to ``client.{ops}.{op_method}``."""\n'
        + create_body
        + "\n"
    )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def _immediate_child_segments(
    prefix: Tuple[str, ...], tree_keys: Set[Tuple[str, ...]]
) -> List[str]:
    plen = len(prefix)
    kids: Set[str] = set()
    for k in tree_keys:
        if len(k) == plen + 1 and k[:plen] == prefix:
            kids.add(k[-1])
    return sorted(kids)


def _write_namespace_init(
    init_path: Path,
    prefix: Tuple[str, ...],
    children: List[str],
    *,
    async_mode: bool,
) -> None:
    parent_seg = prefix[-1]
    parent_class = _pascal_class_name(parent_seg)
    imp = "from pydo.aio import Client" if async_mode else "from pydo import Client"
    needs_generate_alias = parent_seg == "images" and "generations" in children
    lines = [
        INIT_HEADER,
        "",
        imp,
    ]
    if needs_generate_alias:
        lines.append("from typing import Any")
    for c in children:
        lines.append(f"from .{c} import {_pascal_class_name(c)}")
    lines.extend(
        [
            "",
            "",
            f"class {parent_class}:",
            '    """Inference path namespace (generated)."""',
            "",
            "    def __init__(self, client: Client) -> None:",
        ]
    )
    for c in children:
        cc = _pascal_class_name(c)
        lines.append(f"        self.{c} = {cc}(client)")
    if needs_generate_alias:
        async_kw = "async " if async_mode else ""
        ret_kw = "await " if async_mode else ""
        lines.append("")
        lines.append(f"    {async_kw}def generate(self, **kwargs: Any) -> Any:")
        lines.append(
            '        """Alias for ``images.generations.generate`` '
            '(``POST /v1/images/generations``)."""'
        )
        lines.append(
            f"        return {ret_kw}self.generations.generate(**kwargs)\n"
        )
    lines.append("")
    lines.append(f'__all__ = ["{parent_class}"]')
    lines.append("")
    init_path.write_text("\n".join(lines), encoding="utf-8")


def _collect_ops_by_group(
    builders: List[Tuple[str, str, str]],
) -> Dict[str, List[OpSpec]]:
    by_group: Dict[str, List[OpSpec]] = {}
    for group, op_method, url in builders:
        segs = _path_segments(url)
        if not segs:
            raise RuntimeError(f"no segments for {url!r} ({group}.{op_method})")
        by_group.setdefault(group, []).append(
            OpSpec(group=group, op_method=op_method, segments=segs)
        )
    return by_group


def _build_tree_keys(specs: List[OpSpec]) -> Set[Tuple[str, ...]]:
    keys: Set[Tuple[str, ...]] = set()
    for s in specs:
        for i in range(len(s.segments)):
            keys.add(tuple(s.segments[: i + 1]))
    return keys


def _write_package_init_with_facade(
    init_path: Path,
    top_segments: List[str],
    *,
    class_name: str,
    async_mode: bool,
) -> None:
    """Write package ``__init__.py`` with the top-level resource root class."""
    imp = "from pydo.aio import Client" if async_mode else "from pydo import Client"
    lines = [
        INIT_HEADER,
        "",
        imp,
    ]
    for seg in sorted(top_segments):
        cls = _pascal_class_name(seg)
        lines.append(f"from .{seg} import {cls}")
    lines.extend(
        [
            "",
            "",
            f"class {class_name}:",
            '    """Nested inference resource root (generated)."""',
            "",
            "    def __init__(self, client: Client) -> None:",
        ]
    )
    for seg in sorted(top_segments):
        cls = _pascal_class_name(seg)
        lines.append(f"        self.{seg} = {cls}(client)")
    lines.append("")
    lines.append(f'__all__ = ["{class_name}"]')
    lines.append("")
    init_path.write_text("\n".join(lines), encoding="utf-8")


def _write_empty_package_init(base: Path, *, class_name: str, async_mode: bool) -> None:
    base.mkdir(parents=True, exist_ok=True)
    imp = "from pydo.aio import Client" if async_mode else "from pydo import Client"
    (base / "__init__.py").write_text(
        INIT_HEADER
        + "\n"
        + f"{imp}\n"
        + "\n\n"
        + f"class {class_name}:\n"
        + '    """Nested inference resource root (no operations in spec)."""\n'
        + "\n"
        + "    def __init__(self, client: Client) -> None:\n"
        + "        self._client = client\n"
        + "\n"
        + f'__all__ = ["{class_name}"]\n',
        encoding="utf-8",
    )


def _emit_group(
    base: Path,
    specs: List[OpSpec],
    *,
    facade_class: str,
    async_mode: bool,
) -> List[str]:
    """Return sorted top-level URL segments (first path component after ``/v1``)."""
    if not specs:
        _write_empty_package_init(base, class_name=facade_class, async_mode=async_mode)
        return []

    leaf_by_path: Dict[Tuple[str, ...], OpSpec] = {}
    for s in specs:
        key = tuple(s.segments)
        if key in leaf_by_path:
            raise RuntimeError(
                f"duplicate inference path {key!r}: "
                f"{leaf_by_path[key].op_method} vs {s.op_method}"
            )
        leaf_by_path[key] = s

    tree_keys = _build_tree_keys(specs)

    for path_tuple, spec in leaf_by_path.items():
        *parents, leaf_seg = path_tuple
        leaf_class = _pascal_class_name(leaf_seg)
        if parents:
            rel = Path(*parents) / f"{leaf_seg}.py"
        else:
            rel = Path(f"{leaf_seg}.py")
        if (
            not parents
            and leaf_seg == "async_invoke"
            and spec.op_method == "create_async_invoke"
        ):
            _write_async_invoke_leaf_class(
                base / rel,
                group=spec.group,
                async_mode=async_mode,
            )
        else:
            _write_leaf_class(
                base / rel,
                group=spec.group,
                op_method=spec.op_method,
                facade_method=_facade_method_name(spec.op_method),
                class_name=leaf_class,
                async_mode=async_mode,
            )

    for prefix in sorted(tree_keys, key=lambda x: len(x), reverse=True):
        if prefix in leaf_by_path:
            continue
        children = _immediate_child_segments(prefix, tree_keys)
        if not children:
            continue
        init_dir = base.joinpath(*prefix)
        init_dir.mkdir(parents=True, exist_ok=True)
        _write_namespace_init(
            init_dir / "__init__.py",
            prefix,
            children,
            async_mode=async_mode,
        )

    top_segments = sorted({s.segments[0] for s in specs})
    _write_package_init_with_facade(
        base / "__init__.py",
        top_segments,
        class_name=facade_class,
        async_mode=async_mode,
    )
    return top_segments


def _write_client_surface(
    path: Path,
    inference_top_segments: List[str],
) -> None:
    """Emit mixin classes merged into :class:`pydo.Client` (sync and async both use this file)."""
    lines: List[str] = [
        INIT_HEADER,
        "",
        "from typing import Any",
        "",
        "",
        "class InferenceClientSurface:",
        '    """Generated shortcuts for serverless inference (discovered from the published spec)."""',
        "",
    ]
    # ``images`` is handled manually in Client.__init__ (reassigned after
    # GeneratedClient sets self.images = ImagesOperations).  A @property
    # would block that assignment since it has no setter.
    skip_surface_segments = frozenset({"images"})

    for seg in inference_top_segments:
        if not seg.isidentifier() or seg in skip_surface_segments:
            continue
        lines.append("    @property")
        lines.append(f"    def {seg}(self) -> Any:")
        lines.append(
            f'        """Nested serverless inference API under path segment ``{seg}``."""\n'
        )
        lines.append(f"        return self._require_inference_resource_root().{seg}\n")
    if "async_invoke" in inference_top_segments:
        lines.append("    @property")
        lines.append("    def audio(self) -> Any:")
        lines.append(
            '        """Audio namespace (TTS + generation via async-invoke)."""\n'
        )
        lines.append(
            "        return self._require_inference_resource_root().async_invoke.audio\n"
        )
        lines.append("    @property")
        lines.append("    def speech(self) -> Any:")
        lines.append(
            '        """TTS entry: same as ``audio.speech`` (async-invoke)."""\n'
        )
        lines.append(
            "        return self._require_inference_resource_root().async_invoke.audio.speech\n"
        )
        lines.append("    @property")
        lines.append("    def async_images(self) -> Any:")
        lines.append(
            '        """Async image generation: same as ``async_invoke.images``."""\n'
        )
        lines.append(
            "        return self._require_inference_resource_root().async_invoke.images\n"
        )
    if "images" in inference_top_segments:
        lines.append("    @property")
        lines.append("    def image_generations(self) -> Any:")
        lines.append(
            '        """Explicit ``images.generations`` (sync ``POST /v1/images/generations``)."""\n'
        )
        lines.append(
            "        return self._require_inference_resource_root().images.generations\n"
        )
    lines.append("    @property")
    lines.append("    def inference_layout(self) -> Any:")
    lines.append(
        '        """Full nested serverless inference layout (same objects as the shortcuts above)."""\n'
    )
    lines.append("        return self._require_inference_resource_root()\n")
    lines.extend(
        [
            "",
            "",
            "class AgentClientSurface:",
            '    """Generated shortcut for agent inference operations."""',
            "",
            "    @property",
            "    def agent(self) -> Any:",
            '        """Nested agent inference API (``agent_inference`` operation group)."""\n',
            "        return self._require_agent_inference_resource_root()",
            "",
            "",
            '__all__ = ["AgentClientSurface", "InferenceClientSurface"]',
            "",
        ]
    )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")


def _write_inference_surface_manifest(
    path: Path,
    by_group: Dict[str, List[OpSpec]],
) -> None:
    """Machine-readable list of discovered inference operations (for docs / tooling)."""
    payload: Dict[str, Any] = {
        "source": "operations/_operations.py build_inference_* / build_agent_inference_*",
        "inference": [],
        "agent_inference": [],
    }
    for spec in by_group.get("inference", []):
        payload["inference"].append(
            {
                "op_method": spec.op_method,
                "path_segments": spec.segments,
                "facade_method": _facade_method_name(spec.op_method),
            }
        )
    for spec in by_group.get("agent_inference", []):
        payload["agent_inference"].append(
            {
                "op_method": spec.op_method,
                "path_segments": spec.segments,
                "facade_method": _facade_method_name(spec.op_method),
            }
        )
    path.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")


def main() -> None:
    if not OPS_PATH.is_file():
        raise SystemExit(f"missing {OPS_PATH}")

    if OUT_ROOT.exists():
        shutil.rmtree(OUT_ROOT)

    builders = _parse_builders(OPS_PATH)
    by_group = _collect_ops_by_group(builders)

    OUT_ROOT.mkdir(parents=True, exist_ok=True)

    inference_top = _emit_group(
        OUT_ROOT / "inference",
        by_group.get("inference", []),
        facade_class="InferenceResources",
        async_mode=False,
    )
    _emit_group(
        OUT_ROOT / "agent_inference",
        by_group.get("agent_inference", []),
        facade_class="AgentInferenceResources",
        async_mode=False,
    )
    _write_client_surface(OUT_ROOT / "client_surface.py", inference_top)
    _write_inference_surface_manifest(OUT_ROOT / "inference_surface.json", by_group)

    aio_root = OUT_ROOT / "aio"
    aio_root.mkdir(parents=True, exist_ok=True)
    _emit_group(
        aio_root / "inference",
        by_group.get("inference", []),
        facade_class="InferenceResources",
        async_mode=True,
    )
    _emit_group(
        aio_root / "agent_inference",
        by_group.get("agent_inference", []),
        facade_class="AgentInferenceResources",
        async_mode=True,
    )
    (aio_root / "__init__.py").write_text(
        INIT_HEADER
        + '\n"""Async inference resource packages (e.g. ``pydo.resources.aio.inference``)."""\n'
        "\n"
        "__all__ = []\n",
        encoding="utf-8",
    )

    (OUT_ROOT / "__init__.py").write_text(
        INIT_HEADER
        + '\n"""Nested inference packages: ``inference/``, ``agent_inference/``, ``aio/``."""\n'
        "\n"
        "__all__ = []\n",
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
