#!/usr/bin/env python3
# ------------------------------------
# Copyright (c) DigitalOcean.
# Licensed under the Apache-2.0 License.
# ------------------------------------
"""Emit ``src/pydo/types/`` — typed DotDict subclasses for inference responses.

**Fully automated**: reads the OpenAPI YAML spec, discovers every
``inference_*`` / ``agentInference_*`` operation, collects their response
``$ref`` schemas (plus one level of sub-refs), extracts property definitions,
and generates typed Python classes that mirror the ``openai.types`` layout::

    from pydo.types.chat import ChatCompletion, ChatCompletionChunk
    from pydo.types.images import ImagesResponse, Image
    from pydo.types import ChatCompletion  # top-level re-export

Also emits ``_type_registry.py`` so that :func:`pydo.custom_extensions._wrap`
auto-dispatches JSON responses with a known ``object`` field
(e.g. ``"chat.completion"``) to the correct typed subclass.

Run after the OpenAPI spec is updated (or alongside ``generate_inference_resources.py``).
"""
from __future__ import annotations

import re
import shutil
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, List, Set, Tuple

ROOT = Path(__file__).resolve().parents[1]
SPEC_PATH = ROOT / "DigitalOcean-public.v2.yaml"
TYPES_ROOT = ROOT / "src/pydo/types"

INIT_HEADER = (
    "# ------------------------------------\n"
    "# Copyright (c) DigitalOcean.\n"
    "# Licensed under the Apache-2.0 License.\n"
    "# ------------------------------------\n"
    "# Generated by scripts/generate_inference_types.py — do not edit.\n"
    "from __future__ import annotations\n"
)

# ---------------------------------------------------------------------------
# YAML property extraction (lightweight, no pyyaml dependency)
# ---------------------------------------------------------------------------

_YAML_TYPE_MAP = {
    "string": "str",
    "integer": "int",
    "number": "float",
    "boolean": "bool",
    "array": "List[Any]",
    "object": "Any",
}


@dataclass
class SchemaProp:
    name: str
    py_type: str
    description: str
    nullable: bool


def _indent_level(line: str) -> int:
    return len(line) - len(line.lstrip())


def _schema_to_class_name(schema_name: str) -> str:
    """``chat_completion_response`` → ``ChatCompletionResponse``."""
    return "".join(w.capitalize() for w in schema_name.split("_"))


def _extract_schema_props(spec_text: str, schema_name: str) -> List[SchemaProp]:
    """Extract top-level properties from a named schema in the OpenAPI YAML.

    Only reads *direct* property metadata (one indentation level deeper than
    the property name).  Nested ``items`` / sub-object properties are ignored.
    """
    anchor = re.compile(rf"^    {re.escape(schema_name)}:\s*$", re.MULTILINE)
    m = anchor.search(spec_text)
    if not m:
        return []

    start = m.end()
    props_match = re.search(r"^      properties:\s*$", spec_text[start:], re.MULTILINE)
    if not props_match:
        return []

    props_start = start + props_match.end()
    next_schema = re.search(r"^\s{4}\w", spec_text[props_start:], re.MULTILINE)
    end = props_start + next_schema.start() if next_schema else len(spec_text)
    block_lines = spec_text[props_start:end].split("\n")

    prop_indent = 8
    meta_indent = 10

    result: List[SchemaProp] = []
    i = 0
    while i < len(block_lines):
        line = block_lines[i]
        indent = _indent_level(line)
        stripped = line.strip()

        if indent == prop_indent and re.match(r"\w+:\s*$", stripped):
            prop_name = stripped.rstrip(": ")
            py_type = "Any"
            desc = ""
            nullable = False
            i += 1
            while i < len(block_lines):
                mline = block_lines[i]
                mindent = _indent_level(mline)
                if mindent <= prop_indent and mline.strip():
                    break
                if mindent == meta_indent:
                    ms = mline.strip()
                    tm = re.match(r"type:\s+(\w+)", ms)
                    if tm:
                        py_type = _YAML_TYPE_MAP.get(tm.group(1), "Any")
                    dm = re.match(r"description:\s+(.+)", ms)
                    if dm:
                        d = dm.group(1).strip()
                        if not d.startswith(">") and not d.startswith("|"):
                            desc = d.rstrip(".")
                    if re.match(r"nullable:\s+true", ms):
                        nullable = True
                    rm = re.match(
                        r"""\$ref:\s+['"]#/components/schemas/(\w+)['"]""", ms
                    )
                    if rm:
                        py_type = f'"{_schema_to_class_name(rm.group(1))}"'
                i += 1
            result.append(SchemaProp(prop_name, py_type, desc, nullable))
        else:
            i += 1
    return result


# ---------------------------------------------------------------------------
# Auto-discovery: scan the OpenAPI spec for inference response schemas
# ---------------------------------------------------------------------------

# Friendly overrides: ``schema_name`` → short Python class name.
# Falls back to PascalCase of the schema name if not listed here.
_CLASS_NAME_OVERRIDES: Dict[str, str] = {
    "chat_completion_response": "ChatCompletion",
    "chat_completion_chunk": "ChatCompletionChunk",
    "completion_usage": "CompletionUsage",
    "generated_image": "Image",
    "create_response_response": "Response",
    "create_response_stream_response": "ResponseStreamChunk",
}


def _friendly_class_name(schema_name: str) -> str:
    return _CLASS_NAME_OVERRIDES.get(schema_name, _schema_to_class_name(schema_name))


def _discover_inference_operations(
    spec_text: str,
) -> List[Tuple[str, str, List[str]]]:
    """Return ``[(group, op, [response_schema_names, ...])]`` for inference ops."""
    op_re = re.compile(r"operationId:\s+(inference|agentInference)_(\w+)")
    ref_re = re.compile(r"""\$ref:\s+['"]#/components/schemas/(\w+)['"]""")
    matches = list(op_re.finditer(spec_text))

    results: List[Tuple[str, str, List[str]]] = []
    for i, m in enumerate(matches):
        group, op = m.group(1), m.group(2)
        start = m.start()
        end = matches[i + 1].start() if i + 1 < len(matches) else start + 5000
        block = spec_text[start:end]

        resp_idx = block.find("responses:")
        if resp_idx == -1:
            continue
        resp_block = block[resp_idx:]
        for boundary in ("x-codeSamples:", "security:", "  /"):
            bnd = resp_block.find(boundary, 20)
            if bnd > 0:
                resp_block = resp_block[:bnd]
                break

        schemas = ref_re.findall(resp_block)
        schemas = [s for s in schemas if not s.endswith("_request")]
        if schemas:
            results.append((group, op, schemas))
    return results


def _find_sub_refs(spec_text: str, schema_name: str) -> List[str]:
    """Return ``$ref`` schema names referenced directly inside *schema_name*."""
    anchor = re.search(
        rf"^    {re.escape(schema_name)}:", spec_text, re.MULTILINE
    )
    if not anchor:
        return []
    start = anchor.end()
    nxt = re.search(r"^    \w", spec_text[start:], re.MULTILINE)
    end = start + nxt.start() if nxt else len(spec_text)
    block = spec_text[start:end]
    return re.findall(r"""\$ref:\s+['"]#/components/schemas/(\w+)['"]""", block)


def _detect_object_enum(spec_text: str, schema_name: str) -> str:
    """Return the ``object`` field's enum value (e.g. ``"chat.completion"``), or ``""``."""
    anchor = re.search(
        rf"^    {re.escape(schema_name)}:", spec_text, re.MULTILINE
    )
    if not anchor:
        return ""
    start = anchor.end()
    nxt = re.search(r"^    \w", spec_text[start:], re.MULTILINE)
    end = start + nxt.start() if nxt else len(spec_text)
    block = spec_text[start:end]
    obj_m = re.search(r"^\s{8}object:\s*$", block, re.MULTILINE)
    if not obj_m:
        return ""
    enum_block = block[obj_m.end() : obj_m.end() + 200]
    enum_m = re.search(r"enum:\s*\n\s+- (.+)", enum_block)
    return enum_m.group(1).strip() if enum_m else ""


def _url_path_to_module(url_path: str) -> str:
    """``/v1/chat/completions`` → ``chat``, ``/v1/async-invoke`` → ``async_invoke``."""
    parts = [p for p in url_path.strip("/").split("/") if p not in ("v1", "api")]
    first = parts[0] if parts else "misc"
    return re.sub(r"[^a-zA-Z0-9_]", "_", first)


@dataclass
class SchemaInfo:
    schema_name: str
    class_name: str
    module: str
    object_value: str


def _discover_types(spec_text: str) -> List[SchemaInfo]:
    """Fully automated: discover all inference response schemas + sub-schemas."""
    ops = _discover_inference_operations(spec_text)

    # Map operationId → URL path (for module grouping)
    path_re = re.compile(r"^  (/v1/[^\s:]+):\s*$", re.MULTILINE)
    op_id_re = re.compile(r"operationId:\s+(inference|agentInference)_(\w+)")
    op_to_module: Dict[str, str] = {}
    for pm in path_re.finditer(spec_text):
        url_path = pm.group(1)
        block = spec_text[pm.end() : pm.end() + 300]
        om = op_id_re.search(block)
        if om:
            op_key = f"{om.group(1)}_{om.group(2)}"
            op_to_module[op_key] = _url_path_to_module(url_path)

    # Collect top-level response schemas and assign them to modules
    schema_to_module: Dict[str, str] = {}
    for group, op, schemas in ops:
        op_key = f"{group}_{op}"
        module = op_to_module.get(op_key, op.split("_")[0])
        for s in schemas:
            schema_to_module.setdefault(s, module)

    # Walk one level of sub-refs and assign to same module as parent
    all_schemas = list(schema_to_module.keys())
    for s in all_schemas:
        sub_refs = _find_sub_refs(spec_text, s)
        parent_module = schema_to_module[s]
        for sr in sub_refs:
            if sr not in schema_to_module and not sr.endswith("_request"):
                schema_to_module[sr] = parent_module

    seen: Set[str] = set()
    result: List[SchemaInfo] = []
    for schema_name in sorted(schema_to_module):
        if schema_name in seen:
            continue
        seen.add(schema_name)
        result.append(
            SchemaInfo(
                schema_name=schema_name,
                class_name=_friendly_class_name(schema_name),
                module=schema_to_module[schema_name],
                object_value=_detect_object_enum(spec_text, schema_name),
            )
        )
    return result


# ---------------------------------------------------------------------------
# Code emission
# ---------------------------------------------------------------------------


def _emit_type_class(
    class_name: str,
    props: List[SchemaProp],
    description: str,
) -> str:
    """Return source for a single typed DotDict subclass."""
    lines = [
        f"class {class_name}(DotDict):",
        f'    """{description}"""',
    ]
    if not props:
        lines.append("    ...")
        return "\n".join(lines) + "\n"

    for p in props:
        ptype = f"Optional[{p.py_type}]" if p.nullable else p.py_type
        comment = f"  # {p.description}" if p.description else ""
        lines.append(f"    {p.name}: {ptype}{comment}")

    return "\n".join(lines) + "\n"


def _emit_types_module(spec_text: str) -> Dict[str, str]:
    """Auto-discover and generate the full types module.

    Returns ``object_value`` → ``full.class.import.path`` for the type registry.
    """
    infos = _discover_types(spec_text)

    by_module: Dict[str, List[SchemaInfo]] = {}
    for info in infos:
        by_module.setdefault(info.module, []).append(info)

    object_type_map: Dict[str, str] = {}

    for module, schemas in sorted(by_module.items()):
        mod_dir = TYPES_ROOT / module
        mod_dir.mkdir(parents=True, exist_ok=True)

        classes: List[str] = []
        all_names: List[str] = []

        for info in schemas:
            props = _extract_schema_props(spec_text, info.schema_name)
            desc = f"Typed response for ``{info.schema_name}`` schema."
            classes.append(_emit_type_class(info.class_name, props, desc))
            all_names.append(info.class_name)

            if info.object_value:
                object_type_map[info.object_value] = (
                    f"pydo.types.{module}.{info.class_name}"
                )

        needs_list = any("List[" in c for c in classes)
        typing_imports = ["Any", "Optional"]
        if needs_list:
            typing_imports.append("List")

        module_text = (
            INIT_HEADER
            + "\n"
            + f"from typing import {', '.join(sorted(typing_imports))}\n\n"
            + "from pydo.custom_extensions import DotDict\n\n\n"
            + "\n\n".join(classes)
            + "\n"
            + f"__all__ = {all_names!r}\n"
        )
        (mod_dir / "__init__.py").write_text(module_text, encoding="utf-8")

    # Top-level __init__.py re-exporting everything
    all_top_level: List[str] = []
    import_lines: List[str] = []
    for module, schemas in sorted(by_module.items()):
        for info in schemas:
            import_lines.append(
                f"from pydo.types.{module} import {info.class_name}"
            )
            all_top_level.append(info.class_name)

    init_text = (
        INIT_HEADER
        + '\n"""Typed response models for inference endpoints (auto-generated).\n\n'
        + "Usage::\n\n"
        + "    from pydo.types.chat import ChatCompletion\n"
        + "    from pydo.types.images import ImagesResponse, Image\n"
        + "    from pydo.types import ChatCompletion  # also works\n"
        + '"""\n\n'
        + "\n".join(import_lines)
        + "\n\n"
        + f"__all__ = {all_top_level!r}\n"
    )
    TYPES_ROOT.mkdir(parents=True, exist_ok=True)
    (TYPES_ROOT / "__init__.py").write_text(init_text, encoding="utf-8")

    return object_type_map


def _write_type_registry(
    path: Path, object_type_map: Dict[str, str]
) -> None:
    """Emit ``_type_registry.py`` mapping ``object`` field values → typed classes."""
    lines = [
        INIT_HEADER,
        "",
        '"""Auto-dispatch: maps the ``object`` field in JSON responses to typed classes."""',
        "",
        "from typing import Dict, Type",
        "",
        "from pydo.custom_extensions import DotDict",
        "",
    ]
    import_set: Dict[str, List[str]] = {}
    for fqn in object_type_map.values():
        mod, cls = fqn.rsplit(".", 1)
        import_set.setdefault(mod, []).append(cls)

    for mod in sorted(import_set):
        classes = ", ".join(sorted(import_set[mod]))
        lines.append(f"from {mod} import {classes}")

    lines.append("")
    lines.append("")
    lines.append("_OBJECT_TYPE_MAP: Dict[str, Type[DotDict]] = {")
    for obj_val, fqn in sorted(object_type_map.items()):
        cls = fqn.rsplit(".", 1)[1]
        lines.append(f'    "{obj_val}": {cls},')
    lines.append("}")
    lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")


# ---------------------------------------------------------------------------
# main
# ---------------------------------------------------------------------------


def main() -> None:
    if not SPEC_PATH.is_file():
        raise SystemExit(
            f"OpenAPI spec not found at {SPEC_PATH}\n"
            "Place DigitalOcean-public.v2.yaml in the repo root."
        )

    spec_text = SPEC_PATH.read_text(encoding="utf-8")

    if TYPES_ROOT.exists():
        shutil.rmtree(TYPES_ROOT)

    object_type_map = _emit_types_module(spec_text)
    _write_type_registry(TYPES_ROOT / "_type_registry.py", object_type_map)

    # Summary
    infos = _discover_types(spec_text)
    by_mod: Dict[str, List[str]] = {}
    for info in infos:
        by_mod.setdefault(info.module, []).append(info.class_name)
    print(f"Generated {len(infos)} types in {TYPES_ROOT}:")
    for mod, classes in sorted(by_mod.items()):
        print(f"  pydo.types.{mod}: {', '.join(classes)}")
    if object_type_map:
        print(f"Type registry: {len(object_type_map)} auto-dispatch entries")


if __name__ == "__main__":
    main()
