# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.9.0, generator: @autorest/python@6.13.16)
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from copy import deepcopy
from typing import Any, Awaitable, TYPE_CHECKING

from azure.core import AsyncPipelineClient
from azure.core.pipeline import policies
from azure.core.rest import AsyncHttpResponse, HttpRequest

from .._serialization import Deserializer, Serializer
from ._configuration import GeneratedClientConfiguration
from .operations import (
    AccountOperations,
    ActionsOperations,
    AddonsOperations,
    AgentInferenceOperations,
    AppsOperations,
    AutoscalepoolsOperations,
    BalanceOperations,
    BillingHistoryOperations,
    BillingInsightsOperations,
    ByoipPrefixesOperations,
    CdnOperations,
    CertificatesOperations,
    DatabasesOperations,
    DedicatedInferencesOperations,
    DomainsOperations,
    DropletActionsOperations,
    DropletsOperations,
    FirewallsOperations,
    FunctionsAccessKeyOperations,
    FunctionsOperations,
    GenaiOperations,
    ImageActionsOperations,
    ImagesOperations,
    InferenceOperations,
    InvoicesOperations,
    KubernetesOperations,
    LoadBalancersOperations,
    MonitoringOperations,
    NfsOperations,
    OneClicksOperations,
    PartnerAttachmentsOperations,
    ProjectsOperations,
    RegionsOperations,
    RegistriesOperations,
    RegistryOperations,
    ReservedIPsActionsOperations,
    ReservedIPsOperations,
    ReservedIPv6ActionsOperations,
    ReservedIPv6Operations,
    SecurityOperations,
    SizesOperations,
    SnapshotsOperations,
    SpacesKeyOperations,
    SshKeysOperations,
    TagsOperations,
    UptimeOperations,
    VectorDatabasesOperations,
    VolumeActionsOperations,
    VolumeSnapshotsOperations,
    VolumesOperations,
    VpcPeeringsOperations,
    VpcnatgatewaysOperations,
    VpcsOperations,
)

if TYPE_CHECKING:
    # pylint: disable=unused-import,ungrouped-imports
    from azure.core.credentials_async import AsyncTokenCredential


class GeneratedClient:  # pylint: disable=client-accepts-api-version-keyword,too-many-instance-attributes
    """GeneratedClient.

    :ivar one_clicks: OneClicksOperations operations
    :vartype one_clicks: pydo.aio.operations.OneClicksOperations
    :ivar account: AccountOperations operations
    :vartype account: pydo.aio.operations.AccountOperations
    :ivar ssh_keys: SshKeysOperations operations
    :vartype ssh_keys: pydo.aio.operations.SshKeysOperations
    :ivar actions: ActionsOperations operations
    :vartype actions: pydo.aio.operations.ActionsOperations
    :ivar addons: AddonsOperations operations
    :vartype addons: pydo.aio.operations.AddonsOperations
    :ivar apps: AppsOperations operations
    :vartype apps: pydo.aio.operations.AppsOperations
    :ivar cdn: CdnOperations operations
    :vartype cdn: pydo.aio.operations.CdnOperations
    :ivar certificates: CertificatesOperations operations
    :vartype certificates: pydo.aio.operations.CertificatesOperations
    :ivar balance: BalanceOperations operations
    :vartype balance: pydo.aio.operations.BalanceOperations
    :ivar billing_history: BillingHistoryOperations operations
    :vartype billing_history: pydo.aio.operations.BillingHistoryOperations
    :ivar invoices: InvoicesOperations operations
    :vartype invoices: pydo.aio.operations.InvoicesOperations
    :ivar billing_insights: BillingInsightsOperations operations
    :vartype billing_insights: pydo.aio.operations.BillingInsightsOperations
    :ivar databases: DatabasesOperations operations
    :vartype databases: pydo.aio.operations.DatabasesOperations
    :ivar dedicated_inferences: DedicatedInferencesOperations operations
    :vartype dedicated_inferences: pydo.aio.operations.DedicatedInferencesOperations
    :ivar domains: DomainsOperations operations
    :vartype domains: pydo.aio.operations.DomainsOperations
    :ivar droplets: DropletsOperations operations
    :vartype droplets: pydo.aio.operations.DropletsOperations
    :ivar droplet_actions: DropletActionsOperations operations
    :vartype droplet_actions: pydo.aio.operations.DropletActionsOperations
    :ivar autoscalepools: AutoscalepoolsOperations operations
    :vartype autoscalepools: pydo.aio.operations.AutoscalepoolsOperations
    :ivar firewalls: FirewallsOperations operations
    :vartype firewalls: pydo.aio.operations.FirewallsOperations
    :ivar functions: FunctionsOperations operations
    :vartype functions: pydo.aio.operations.FunctionsOperations
    :ivar functions_access_key: FunctionsAccessKeyOperations operations
    :vartype functions_access_key: pydo.aio.operations.FunctionsAccessKeyOperations
    :ivar images: ImagesOperations operations
    :vartype images: pydo.aio.operations.ImagesOperations
    :ivar image_actions: ImageActionsOperations operations
    :vartype image_actions: pydo.aio.operations.ImageActionsOperations
    :ivar kubernetes: KubernetesOperations operations
    :vartype kubernetes: pydo.aio.operations.KubernetesOperations
    :ivar load_balancers: LoadBalancersOperations operations
    :vartype load_balancers: pydo.aio.operations.LoadBalancersOperations
    :ivar monitoring: MonitoringOperations operations
    :vartype monitoring: pydo.aio.operations.MonitoringOperations
    :ivar nfs: NfsOperations operations
    :vartype nfs: pydo.aio.operations.NfsOperations
    :ivar partner_attachments: PartnerAttachmentsOperations operations
    :vartype partner_attachments: pydo.aio.operations.PartnerAttachmentsOperations
    :ivar projects: ProjectsOperations operations
    :vartype projects: pydo.aio.operations.ProjectsOperations
    :ivar regions: RegionsOperations operations
    :vartype regions: pydo.aio.operations.RegionsOperations
    :ivar registries: RegistriesOperations operations
    :vartype registries: pydo.aio.operations.RegistriesOperations
    :ivar registry: RegistryOperations operations
    :vartype registry: pydo.aio.operations.RegistryOperations
    :ivar reserved_ips: ReservedIPsOperations operations
    :vartype reserved_ips: pydo.aio.operations.ReservedIPsOperations
    :ivar reserved_ips_actions: ReservedIPsActionsOperations operations
    :vartype reserved_ips_actions: pydo.aio.operations.ReservedIPsActionsOperations
    :ivar reserved_ipv6: ReservedIPv6Operations operations
    :vartype reserved_ipv6: pydo.aio.operations.ReservedIPv6Operations
    :ivar reserved_ipv6_actions: ReservedIPv6ActionsOperations operations
    :vartype reserved_ipv6_actions: pydo.aio.operations.ReservedIPv6ActionsOperations
    :ivar byoip_prefixes: ByoipPrefixesOperations operations
    :vartype byoip_prefixes: pydo.aio.operations.ByoipPrefixesOperations
    :ivar security: SecurityOperations operations
    :vartype security: pydo.aio.operations.SecurityOperations
    :ivar sizes: SizesOperations operations
    :vartype sizes: pydo.aio.operations.SizesOperations
    :ivar snapshots: SnapshotsOperations operations
    :vartype snapshots: pydo.aio.operations.SnapshotsOperations
    :ivar spaces_key: SpacesKeyOperations operations
    :vartype spaces_key: pydo.aio.operations.SpacesKeyOperations
    :ivar tags: TagsOperations operations
    :vartype tags: pydo.aio.operations.TagsOperations
    :ivar vector_databases: VectorDatabasesOperations operations
    :vartype vector_databases: pydo.aio.operations.VectorDatabasesOperations
    :ivar volumes: VolumesOperations operations
    :vartype volumes: pydo.aio.operations.VolumesOperations
    :ivar volume_actions: VolumeActionsOperations operations
    :vartype volume_actions: pydo.aio.operations.VolumeActionsOperations
    :ivar volume_snapshots: VolumeSnapshotsOperations operations
    :vartype volume_snapshots: pydo.aio.operations.VolumeSnapshotsOperations
    :ivar vpcs: VpcsOperations operations
    :vartype vpcs: pydo.aio.operations.VpcsOperations
    :ivar vpc_peerings: VpcPeeringsOperations operations
    :vartype vpc_peerings: pydo.aio.operations.VpcPeeringsOperations
    :ivar vpcnatgateways: VpcnatgatewaysOperations operations
    :vartype vpcnatgateways: pydo.aio.operations.VpcnatgatewaysOperations
    :ivar uptime: UptimeOperations operations
    :vartype uptime: pydo.aio.operations.UptimeOperations
    :ivar genai: GenaiOperations operations
    :vartype genai: pydo.aio.operations.GenaiOperations
    :ivar inference: InferenceOperations operations
    :vartype inference: pydo.aio.operations.InferenceOperations
    :ivar agent_inference: AgentInferenceOperations operations
    :vartype agent_inference: pydo.aio.operations.AgentInferenceOperations
    :param credential: Credential needed for the client to connect to Azure. Required.
    :type credential: ~azure.core.credentials_async.AsyncTokenCredential
    :keyword endpoint: Service URL. Default value is "https://api.digitalocean.com".
    :paramtype endpoint: str
    """

    def __init__(
        self,
        credential: "AsyncTokenCredential",
        *,
        endpoint: str = "https://api.digitalocean.com",
        **kwargs: Any
    ) -> None:
        self._config = GeneratedClientConfiguration(credential=credential, **kwargs)
        _policies = kwargs.pop("policies", None)
        if _policies is None:
            _policies = [
                policies.RequestIdPolicy(**kwargs),
                self._config.headers_policy,
                self._config.user_agent_policy,
                self._config.proxy_policy,
                policies.ContentDecodePolicy(**kwargs),
                self._config.redirect_policy,
                self._config.retry_policy,
                self._config.authentication_policy,
                self._config.custom_hook_policy,
                self._config.logging_policy,
                policies.DistributedTracingPolicy(**kwargs),
                (
                    policies.SensitiveHeaderCleanupPolicy(**kwargs)
                    if self._config.redirect_policy
                    else None
                ),
                self._config.http_logging_policy,
            ]
        self._client: AsyncPipelineClient = AsyncPipelineClient(
            base_url=endpoint, policies=_policies, **kwargs
        )

        self._serialize = Serializer()
        self._deserialize = Deserializer()
        self._serialize.client_side_validation = False
        self.one_clicks = OneClicksOperations(
            self._client, self._config, self._serialize, self._deserialize
        )
        self.account = AccountOperations(
            self._client, self._config, self._serialize, self._deserialize
        )
        self.ssh_keys = SshKeysOperations(
            self._client, self._config, self._serialize, self._deserialize
        )
        self.actions = ActionsOperations(
            self._client, self._config, self._serialize, self._deserialize
        )
        self.addons = AddonsOperations(
            self._client, self._config, self._serialize, self._deserialize
        )
        self.apps = AppsOperations(
            self._client, self._config, self._serialize, self._deserialize
        )
        self.cdn = CdnOperations(
            self._client, self._config, self._serialize, self._deserialize
        )
        self.certificates = CertificatesOperations(
            self._client, self._config, self._serialize, self._deserialize
        )
        self.balance = BalanceOperations(
            self._client, self._config, self._serialize, self._deserialize
        )
        self.billing_history = BillingHistoryOperations(
            self._client, self._config, self._serialize, self._deserialize
        )
        self.invoices = InvoicesOperations(
            self._client, self._config, self._serialize, self._deserialize
        )
        self.billing_insights = BillingInsightsOperations(
            self._client, self._config, self._serialize, self._deserialize
        )
        self.databases = DatabasesOperations(
            self._client, self._config, self._serialize, self._deserialize
        )
        self.dedicated_inferences = DedicatedInferencesOperations(
            self._client, self._config, self._serialize, self._deserialize
        )
        self.domains = DomainsOperations(
            self._client, self._config, self._serialize, self._deserialize
        )
        self.droplets = DropletsOperations(
            self._client, self._config, self._serialize, self._deserialize
        )
        self.droplet_actions = DropletActionsOperations(
            self._client, self._config, self._serialize, self._deserialize
        )
        self.autoscalepools = AutoscalepoolsOperations(
            self._client, self._config, self._serialize, self._deserialize
        )
        self.firewalls = FirewallsOperations(
            self._client, self._config, self._serialize, self._deserialize
        )
        self.functions = FunctionsOperations(
            self._client, self._config, self._serialize, self._deserialize
        )
        self.functions_access_key = FunctionsAccessKeyOperations(
            self._client, self._config, self._serialize, self._deserialize
        )
        self.images = ImagesOperations(
            self._client, self._config, self._serialize, self._deserialize
        )
        self.image_actions = ImageActionsOperations(
            self._client, self._config, self._serialize, self._deserialize
        )
        self.kubernetes = KubernetesOperations(
            self._client, self._config, self._serialize, self._deserialize
        )
        self.load_balancers = LoadBalancersOperations(
            self._client, self._config, self._serialize, self._deserialize
        )
        self.monitoring = MonitoringOperations(
            self._client, self._config, self._serialize, self._deserialize
        )
        self.nfs = NfsOperations(
            self._client, self._config, self._serialize, self._deserialize
        )
        self.partner_attachments = PartnerAttachmentsOperations(
            self._client, self._config, self._serialize, self._deserialize
        )
        self.projects = ProjectsOperations(
            self._client, self._config, self._serialize, self._deserialize
        )
        self.regions = RegionsOperations(
            self._client, self._config, self._serialize, self._deserialize
        )
        self.registries = RegistriesOperations(
            self._client, self._config, self._serialize, self._deserialize
        )
        self.registry = RegistryOperations(
            self._client, self._config, self._serialize, self._deserialize
        )
        self.reserved_ips = ReservedIPsOperations(
            self._client, self._config, self._serialize, self._deserialize
        )
        self.reserved_ips_actions = ReservedIPsActionsOperations(
            self._client, self._config, self._serialize, self._deserialize
        )
        self.reserved_ipv6 = ReservedIPv6Operations(
            self._client, self._config, self._serialize, self._deserialize
        )
        self.reserved_ipv6_actions = ReservedIPv6ActionsOperations(
            self._client, self._config, self._serialize, self._deserialize
        )
        self.byoip_prefixes = ByoipPrefixesOperations(
            self._client, self._config, self._serialize, self._deserialize
        )
        self.security = SecurityOperations(
            self._client, self._config, self._serialize, self._deserialize
        )
        self.sizes = SizesOperations(
            self._client, self._config, self._serialize, self._deserialize
        )
        self.snapshots = SnapshotsOperations(
            self._client, self._config, self._serialize, self._deserialize
        )
        self.spaces_key = SpacesKeyOperations(
            self._client, self._config, self._serialize, self._deserialize
        )
        self.tags = TagsOperations(
            self._client, self._config, self._serialize, self._deserialize
        )
        self.vector_databases = VectorDatabasesOperations(
            self._client, self._config, self._serialize, self._deserialize
        )
        self.volumes = VolumesOperations(
            self._client, self._config, self._serialize, self._deserialize
        )
        self.volume_actions = VolumeActionsOperations(
            self._client, self._config, self._serialize, self._deserialize
        )
        self.volume_snapshots = VolumeSnapshotsOperations(
            self._client, self._config, self._serialize, self._deserialize
        )
        self.vpcs = VpcsOperations(
            self._client, self._config, self._serialize, self._deserialize
        )
        self.vpc_peerings = VpcPeeringsOperations(
            self._client, self._config, self._serialize, self._deserialize
        )
        self.vpcnatgateways = VpcnatgatewaysOperations(
            self._client, self._config, self._serialize, self._deserialize
        )
        self.uptime = UptimeOperations(
            self._client, self._config, self._serialize, self._deserialize
        )
        self.genai = GenaiOperations(
            self._client, self._config, self._serialize, self._deserialize
        )
        self.inference = InferenceOperations(
            self._client, self._config, self._serialize, self._deserialize
        )
        self.agent_inference = AgentInferenceOperations(
            self._client, self._config, self._serialize, self._deserialize
        )

    def send_request(
        self, request: HttpRequest, *, stream: bool = False, **kwargs: Any
    ) -> Awaitable[AsyncHttpResponse]:
        """Runs the network request through the client's chained policies.

        >>> from azure.core.rest import HttpRequest
        >>> request = HttpRequest("GET", "https://www.example.org/")
        <HttpRequest [GET], url: 'https://www.example.org/'>
        >>> response = await client.send_request(request)
        <AsyncHttpResponse: 200 OK>

        For more information on this code flow, see https://aka.ms/azsdk/dpcodegen/python/send_request

        :param request: The network request you want to make. Required.
        :type request: ~azure.core.rest.HttpRequest
        :keyword bool stream: Whether the response payload will be streamed. Defaults to False.
        :return: The response of your network call. Does not do error handling on your response.
        :rtype: ~azure.core.rest.AsyncHttpResponse
        """

        request_copy = deepcopy(request)
        request_copy.url = self._client.format_url(request_copy.url)
        return self._client.send_request(request_copy, stream=stream, **kwargs)  # type: ignore

    async def close(self) -> None:
        await self._client.close()

    async def __aenter__(self) -> "GeneratedClient":
        await self._client.__aenter__()
        return self

    async def __aexit__(self, *exc_details: Any) -> None:
        await self._client.__aexit__(*exc_details)
