# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.9.0, generator: @autorest/python@6.13.16)
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from ._operations import OneClicksOperations
from ._operations import AccountOperations
from ._operations import SshKeysOperations
from ._operations import ActionsOperations
from ._operations import AppsOperations
from ._operations import CdnOperations
from ._operations import CertificatesOperations
from ._operations import BalanceOperations
from ._operations import BillingHistoryOperations
from ._operations import InvoicesOperations
from ._operations import DatabasesOperations
from ._operations import DomainsOperations
from ._operations import DropletsOperations
from ._operations import DropletActionsOperations
from ._operations import FirewallsOperations
from ._operations import FunctionsOperations
from ._operations import ImagesOperations
from ._operations import ImageActionsOperations
from ._operations import KubernetesOperations
from ._operations import LoadBalancersOperations
from ._operations import MonitoringOperations
from ._operations import ProjectsOperations
from ._operations import RegionsOperations
from ._operations import RegistryOperations
from ._operations import ReservedIPsOperations
from ._operations import ReservedIPsActionsOperations
from ._operations import SizesOperations
from ._operations import SnapshotsOperations
from ._operations import TagsOperations
from ._operations import VolumesOperations
from ._operations import VolumeActionsOperations
from ._operations import VolumeSnapshotsOperations
from ._operations import VpcsOperations
from ._operations import VpcPeeringsOperations
from ._operations import UptimeOperations

from ._patch import __all__ as _patch_all
from ._patch import *  # pylint: disable=unused-wildcard-import
from ._patch import patch_sdk as _patch_sdk

__all__ = [
    "OneClicksOperations",
    "AccountOperations",
    "SshKeysOperations",
    "ActionsOperations",
    "AppsOperations",
    "CdnOperations",
    "CertificatesOperations",
    "BalanceOperations",
    "BillingHistoryOperations",
    "InvoicesOperations",
    "DatabasesOperations",
    "DomainsOperations",
    "DropletsOperations",
    "DropletActionsOperations",
    "FirewallsOperations",
    "FunctionsOperations",
    "ImagesOperations",
    "ImageActionsOperations",
    "KubernetesOperations",
    "LoadBalancersOperations",
    "MonitoringOperations",
    "ProjectsOperations",
    "RegionsOperations",
    "RegistryOperations",
    "ReservedIPsOperations",
    "ReservedIPsActionsOperations",
    "SizesOperations",
    "SnapshotsOperations",
    "TagsOperations",
    "VolumesOperations",
    "VolumeActionsOperations",
    "VolumeSnapshotsOperations",
    "VpcsOperations",
    "VpcPeeringsOperations",
    "UptimeOperations",
]
__all__.extend([p for p in _patch_all if p not in __all__])
_patch_sdk()
