# ------------------------------------
# Copyright (c) DigitalOcean.
# Licensed under the Apache-2.0 License.
# ------------------------------------
# Generated by scripts/generate_inference_resources.py — do not edit.
from __future__ import annotations


from pydo import Client
from .async_invoke import AsyncInvoke
from .batches import Batches
from .chat import Chat
from .embeddings import Embeddings
from .files import Files
from .images import Images
from .messages import Messages
from .models import Models
from .responses import Responses


class InferenceResources:
    """Nested inference resource root (generated)."""

    def __init__(self, client: Client) -> None:
        self.async_invoke = AsyncInvoke(client)
        self.batches = Batches(client)
        self.chat = Chat(client)
        self.embeddings = Embeddings(client)
        self.files = Files(client)
        self.images = Images(client)
        self.messages = Messages(client)
        self.models = Models(client)
        self.responses = Responses(client)


__all__ = ["InferenceResources"]
