# ------------------------------------
# Copyright (c) DigitalOcean.
# Licensed under the Apache-2.0 License.
# ------------------------------------
# Generated by scripts/generate_inference_types.py — do not edit.
from __future__ import annotations

from typing import Any, List, Optional

from pydo.custom_extensions import DotDict


class BatchListResponse(DotDict):
    """Typed response for ``batch_list_response`` schema."""

    object: str  # The object type, always `list`
    data: List[Any]  # Batch jobs on this page, ordered newest first
    first_id: Optional[
        str
    ]  # ID of the first batch on this page. Null when the page is empty
    last_id: Optional[str]
    has_more: bool  # Whether additional batches exist beyond this page


__all__ = ["BatchListResponse"]
