name: pr

on:
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        python-version:
          - "3.9"
          - "3.10"

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry Action
        uses: snok/install-poetry@v1.3.1
        with:
          version: 1.1.13

      - name: Lint tests
        run: make lint-tests
        env:
          PYLINT_ARGS: "--errors-only"

      - name: Run mocked tests
        run: make test-mocked
