# ------------------------------------
# Copyright (c) DigitalOcean.
# Licensed under the Apache-2.0 License.
# ------------------------------------
# Generated by scripts/generate_inference_resources.py — do not edit.
from __future__ import annotations


from pydo.aio import Client
from .chat import Chat


class AgentInferenceResources:
    """Nested inference resource root (generated)."""

    def __init__(self, client: Client) -> None:
        self.chat = Chat(client)


__all__ = ["AgentInferenceResources"]
